package compiler.ffi;

import compiler.ir.Ir.IrNative;
import compiler.ir.Ir.IrType;

/** Emits the C-facing contract for one typed HashLink native library. */
class CHeaderEmitter {
	public static function emit(natives:Array<IrNative>, library:String):String {
		if (library.length == 0)
			throw "FFI library cannot be empty";
		var selected = [for (native in natives) if (native.library == library) native];
		if (selected.length == 0)
			throw 'No typed native declarations found for FFI library "$library"';
		selected.sort(function(left, right) return Reflect.compare(left.symbol, right.symbol));
		var seen:Map<String, String> = [], canonical:Array<String> = [];
		for (native in selected) {
			var signature = signature(native);
			if (seen.exists(native.symbol) && seen.get(native.symbol) != signature)
				throw 'Conflicting FFI declarations for "$library.${native.symbol}"';
			seen.set(native.symbol, signature);
			canonical.push(signature);
		}
		var guard = sanitize(library, true) + "_FFI_H",
			prefix = sanitize(library),
			output = new StringBuf();
		output.add("/* Generated by Haxeon. Do not edit. */\n");
		output.add('#ifndef $guard\n#define $guard\n\n');
		output.add('#include <hl.h>\n\n');
		output.add('#define ${guard}_SIGNATURE 0x${hex(fingerprint(canonical.join("\n")))}u\n\n');
		for (native in selected)
			output.add('HL_PRIM ${cType(native.result, true)} ${prefix}_${native.symbol}(${parameters(native.arguments)});\n');
		if (selected.length > 0)
			output.add("\n");
		for (native in selected)
			output.add('DEFINE_PRIM(${hlType(native.result)}, ${native.symbol}, ${hlArguments(native.arguments)});\n');
		output.add('\n#endif /* $guard */\n');
		return output.toString();
	}

	static function signature(native:IrNative):String
		return native.library
			+ "."
			+ native.symbol
			+ "("
			+ [for (argument in native.arguments) typeName(argument)].join(",") + "):" + typeName(native.result);

	static function parameters(arguments:Array<IrType>):String {
		if (arguments.length == 0)
			return "void";
		return [
			for (index in 0...arguments.length)
				cType(arguments[index], false) + " arg" + index
		].join(", ");
	}

	static function hlArguments(arguments:Array<IrType>):String
		return arguments.length == 0 ? "_NO_ARG" : [for (argument in arguments) hlType(argument)].join(" ");

	static function cType(type:IrType, result:Bool):String
		return switch type {
			case Void if (result): "void";
			case I32: "int";
			case I64: "int64_t";
			case Bool: "bool";
			case F64: "double";
			case Bytes: "vbyte *";
			case ManagedBytes: "void *";
			case Dyn: "vdynamic *";
			case TypeRef: "hl_type *";
			case Array(_): "varray *";
			case Function(_, _): "vclosure *";
			default: throw 'Unsupported FFI C type ${typeName(type)}';
		};

	static function hlType(type:IrType):String
		return switch type {
			case Void: "_VOID";
			case I32: "_I32";
			case I64: "_I64";
			case Bool: "_BOOL";
			case F64: "_F64";
			case Bytes: "_BYTES";
			case ManagedBytes: "_ABSTRACT(realtime_bytes)";
			case Dyn: "_DYN";
			case TypeRef: "_TYPE";
			case Array(element): '_ARR(${hlType(element)})';
			case Function(arguments, result): '_FUN(${hlType(result)}, ${hlArguments(arguments)})';
			default: throw 'Unsupported FFI HashLink type ${typeName(type)}';
		};

	static function typeName(type:IrType):String
		return switch type {
			case Void: "Void";
			case I32: "Int";
			case I64: "haxe.Int64";
			case Bool: "Bool";
			case F64: "Float";
			case Bytes: "Bytes";
			case ManagedBytes: "haxe.io.Bytes";
			case Dyn: "Dynamic";
			case TypeRef: "Type";
			case Array(element): 'Array<${typeName(element)}>';
			case Iterator(element): 'Iterator<${typeName(element)}>';
			case Function(arguments, result): '(${[for (argument in arguments) typeName(argument)].join(",")})->${typeName(result)}';
			case Enum(name): 'Enum<$name>';
			case Obj(name): 'Object<$name>';
			case Abstract(name): 'Abstract<$name>';
			case Virtual(name): 'Virtual<$name>';
		};

	static function sanitize(value:String, uppercase:Bool = false):String {
		var output = new StringBuf();
		for (index in 0...value.length) {
			var code = value.charCodeAt(index),
				valid = code >= "0".code && code <= "9".code || code >= "A".code && code <= "Z".code || code >= "a".code && code <= "z".code;
			if (uppercase && code >= "a".code && code <= "z".code)
				code = code - "a".code + "A".code;
			output.addChar(valid ? code : "_".code);
		}
		return output.toString();
	}

	static function fingerprint(value:String):Int {
		var hash = 0x811C9DC5;
		for (index in 0...value.length) {
			hash = hash ^ value.charCodeAt(index);
			hash = hash * 0x01000193;
		}
		return hash;
	}

	static function hex(value:Int):String {
		var digits = "0123456789ABCDEF", output = "";
		for (shift in 0...8)
			output = digits.charAt((value >>> (shift * 4)) & 15) + output;
		return output;
	}
}
