package compiler.ffi;

import haxe.Json;
import haxe.io.Path;
import sys.FileSystem;
import sys.io.Process;

typedef CLayout = {
	var size:Int;
	var align:Int;
	var offsets:Map<String, Int>;
}

/** Imports the ABI-visible subset of a C header into deterministic raw HXI. */
class CHeaderImporter {
	public static function importHeader(header:String, target:String, includes:Array<String>, clang:String = "clang", ?library:String):String {
		var base = ["-x", "c", "-std=c11", "-target", target];
		for (include in includes)
			base.push('-I$include');
		var process = new Process(clang, base.concat(["-Xclang", "-ast-dump=json", "-fsyntax-only", header])),
			astText = process.stdout.readAll().toString(),
			diagnostics = process.stderr.readAll().toString(),
			exitCode = process.exitCode();
		process.close();
		if (exitCode != 0)
			throw 'Clang could not import $header:\n$diagnostics';
		process = new Process(clang, base.concat(["-Xclang", "-fdump-record-layouts-complete", "-fsyntax-only", header]));
		var layoutText = process.stdout.readAll().toString() + process.stderr.readAll().toString();
		exitCode = process.exitCode();
		process.close();
		if (exitCode != 0)
			throw 'Clang could not calculate layouts for $header';
		var layouts = parseLayouts(layoutText),
			declarations:Array<Dynamic> = [],
			roots = [FileSystem.fullPath(Path.directory(header))];
		for (include in includes)
			roots.push(FileSystem.fullPath(include));
		collect(Json.parse(astText), declarations, roots, FileSystem.fullPath(header));
		declarations.sort(function(left, right) return Reflect.compare(key(left), key(right)));
		var output = new StringBuf(),
			libraryMetadata = library == null ? "" : ' @library("$library")';
		output.add('// Generated by Haxeon from $header for $target. Do not edit.\n');
		output.add('interface ${moduleName(header)} @target("$target")$libraryMetadata {\n');
		for (declaration in declarations)
			emit(declaration, layouts, output);
		output.add("}\n");
		return output.toString();
	}

	static function collect(node:Dynamic, output:Array<Dynamic>, roots:Array<String>, currentFile:String):String {
		if (node == null)
			return currentFile;
		var location:Dynamic = field(node, "loc"),
			locationFile:String = field(location, "file");
		if (locationFile != null)
			currentFile = FileSystem.fullPath(locationFile);
		Reflect.setField(node, "_hxiFile", currentFile);
		var kind:String = field(node, "kind"),
			name:String = field(node, "name");
		if (name != null
			&& !StringTools.startsWith(name, "__")
			&& (kind == "TypedefDecl" || kind == "RecordDecl" || kind == "FunctionDecl" || kind == "EnumDecl" || kind == "EnumConstantDecl")
			&& isUserDeclaration(node, roots, currentFile))
			output.push(node);
		var inner:Array<Dynamic> = field(node, "inner");
		if (inner != null && !(kind == "EnumDecl" && name != null))
			for (child in inner)
				currentFile = collect(child, output, roots, currentFile);
		return currentFile;
	}

	static function emit(node:Dynamic, layouts:Map<String, CLayout>, output:StringBuf):Void {
		var kind:String = field(node, "kind"),
			name:String = field(node, "name"),
			type:Dynamic = field(node, "type");
		switch kind {
			case "EnumDecl":
				var fixed:Dynamic = field(node, "fixedUnderlyingType"), representation = fixed == null ? "c_int" : mapType(field(fixed, "qualType")),
					values = [
						for (child in children(node)) if (field(child, "kind") == "EnumConstantDecl") child
					];
				output.add('\tenum $name : $representation {\n');
				for (entry in values) {
					var entryName:String = field(entry, "name"),
						value = constantValue(entry);
					if (value != null)
						output.add('\t\t$entryName = $value;\n');
				}
				output.add("\t}\n");
			case "EnumConstantDecl":
				var value = constantValue(node);
				if (value != null)
					output.add('\tconst $name = $value;\n');
			case "TypedefDecl":
				var qualified:String = field(type, "qualType");
				if (!StringTools.startsWith(qualified, "struct ") && !StringTools.startsWith(qualified, "enum "))
					output.add('\ttype $name = ${mapType(qualified)};\n');
			case "RecordDecl":
				var fields:Array<Dynamic> = [for (child in children(node)) if (field(child, "kind") == "FieldDecl") child];
				if (fields.length == 0)
					return;
				var layout = layouts.get(name),
					annotation = layout == null ? "" : ' @layout(${layout.size}, ${layout.align})';
				output.add('\tstruct $name$annotation {\n');
				for (entry in fields) {
					var fieldName:String = field(entry, "name"),
						fieldType:Dynamic = field(entry, "type"),
						qualifiedType:String = field(fieldType, "qualType"),
						offset = layout == null ? null : layout.offsets.get(fieldName);
					if (StringTools.endsWith(qualifiedType, "[]"))
						throw '${declarationLocation(entry)}: unsupported flexible array field "$fieldName"';
					output.add('\t\t$fieldName: ${mapType(qualifiedType)}${offset == null ? "" : " @offset(" + offset + ")"};\n');
				}
				output.add("\t}\n");
			case "FunctionDecl":
				if (field(node, "variadic") == true)
					throw '${declarationLocation(node)}: unsupported variadic function "$name"';
				var parameters = [for (child in children(node)) if (field(child, "kind") == "ParmVarDecl") child];
				var signature:String = field(type, "qualType"),
					result = StringTools.trim(signature.substring(0, signature.lastIndexOf("(")));
				output.add('\textern fn $name(');
				output.add([
					for (parameter in parameters)
						'${field(parameter, "name")}: ${mapType(field(field(parameter, "type"), "qualType"))}'
				].join(", "));
				output.add(') -> ${mapType(result)};\n');
		}
	}

	static function mapType(value:String):String {
		value = StringTools.trim(value);
		if (StringTools.endsWith(value, "]")) {
			var split = value.lastIndexOf("[");
			if (split == value.length - 2)
				throw 'Unsupported flexible array type "$value"';
			return 'array<${mapType(value.substring(0, split))}, ${value.substring(split + 1, value.length - 1)}>';
		}
		if (StringTools.endsWith(value, " *"))
			return 'ptr<${mapType(value.substring(0, value.length - 2))}>';
		if (StringTools.startsWith(value, "const "))
			return 'const<${mapType(value.substring(6))}>';
		return switch value {
			case "void": "void";
			case "char": "c_char";
			case "signed char": "c_schar";
			case "unsigned char": "c_uchar";
			case "short": "c_short";
			case "unsigned short": "c_ushort";
			case "int": "c_int";
			case "unsigned int": "c_uint";
			case "long": "c_long";
			case "unsigned long": "c_ulong";
			case "long long": "c_long_long";
			case "unsigned long long": "c_ulong_long";
			case "_Bool": "c_bool";
			case "float": "f32";
			case "double": "f64";
			case "int8_t": "i8";
			case "uint8_t": "u8";
			case "int16_t": "i16";
			case "uint16_t": "u16";
			case "int32_t": "i32";
			case "uint32_t": "u32";
			case "int64_t": "i64";
			case "uint64_t": "u64";
			case "intptr_t": "isize";
			case "uintptr_t": "usize";
			case "size_t": "usize";
			default: StringTools.startsWith(value, "struct ") ? value.substring(7) : StringTools.startsWith(value, "enum ") ? value.substring(5) : value;
		}
	}

	static function parseLayouts(text:String):Map<String, CLayout> {
		var result:Map<String, CLayout> = [],
			current:String = null,
			offsets:Map<String, Int> = [];
		for (line in text.split("\n")) {
			var record = ~/^\s*0 \| struct ([A-Za-z_][A-Za-z0-9_]*)$/;
			if (record.match(line)) {
				current = record.matched(1);
				offsets = [];
				continue;
			}
			if (current == null)
				continue;
			var fieldLine = ~/^\s*([0-9]+) \|\s+.+ ([A-Za-z_][A-Za-z0-9_]*)$/;
			if (fieldLine.match(line))
				offsets.set(fieldLine.matched(2), Std.parseInt(fieldLine.matched(1)));
			var end = ~/\[sizeof=([0-9]+), align=([0-9]+)\]/;
			if (end.match(line)) {
				result.set(current, {size: Std.parseInt(end.matched(1)), align: Std.parseInt(end.matched(2)), offsets: offsets});
				current = null;
			}
		}
		return result;
	}

	static function children(node:Dynamic):Array<Dynamic> {
		var value:Array<Dynamic> = field(node, "inner");
		return value == null ? [] : value;
	}

	static function constantValue(node:Dynamic):Null<String> {
		var value:String = field(node, "value");
		if (value != null)
			return value;
		for (child in children(node)) {
			value = constantValue(child);
			if (value != null)
				return value;
		}
		return null;
	}

	static function field(value:Dynamic, name:String):Dynamic
		return value == null ? null : Reflect.field(value, name);

	static function key(value:Dynamic):String
		return Std.string(field(value, "kind")) + ":" + Std.string(field(value, "name"));

	static function moduleName(path:String):String {
		var name = path.split("/").pop();
		return StringTools.replace(name, ".", "_");
	}

	static function isUserDeclaration(node:Dynamic, roots:Array<String>, currentFile:String):Bool {
		var location:Dynamic = field(node, "loc");
		if (location == null)
			return false;
		for (root in roots)
			if (currentFile == root || StringTools.startsWith(currentFile, root + "/"))
				return true;
		return false;
	}

	static function declarationLocation(node:Dynamic):String {
		var location:Dynamic = field(node, "loc"),
			file:String = field(node, "_hxiFile"),
			line:Dynamic = field(location, "line"),
			column:Dynamic = field(location, "col");
		if (file == null)
			file = "<header>";
		return '$file:${line == null ? "?" : line}:${column == null ? "?" : column}';
	}
}
