package compiler.ffi;

import haxe.Json;
import haxe.Int64;
import haxe.io.Path;
import sys.FileSystem;
import sys.io.File;
import sys.io.Process;

typedef CLayout = {
	var size:Int;
	var align:Int;
	var offsets:Map<String, Int>;
}

/** Imports the ABI-visible subset of a C header into deterministic raw HXI. */
class CHeaderImporter {
	public static function importHeader(header:String, target:String, includes:Array<String>, clang:String = "clang", ?library:String,
			?interfaceName:String):String {
		if (interfaceName != null && !~/^[A-Za-z_][A-Za-z0-9_]*$/.match(interfaceName))
			throw 'Invalid HXI interface name "$interfaceName"';
		var base = ["-x", "c", "-std=c11", "-target", target];
		for (include in includes)
			base.push('-I$include');
		var process = new Process(clang, base.concat(["-Xclang", "-ast-dump=json", "-fsyntax-only", header])),
			astText = process.stdout.readAll().toString(),
			diagnostics = process.stderr.readAll().toString(),
			exitCode = process.exitCode();
		process.close();
		if (exitCode != 0)
			throw 'Clang could not import $header:\n$diagnostics';
		process = new Process(clang, base.concat(["-Xclang", "-fdump-record-layouts-complete", "-fsyntax-only", header]));
		var layoutText = process.stdout.readAll().toString() + process.stderr.readAll().toString();
		exitCode = process.exitCode();
		process.close();
		if (exitCode != 0)
			throw 'Clang could not calculate layouts for $header';
		var layouts = parseLayouts(layoutText),
			declarations:Array<Dynamic> = [],
			roots = [FileSystem.fullPath(Path.directory(header))];
		for (include in includes)
			roots.push(FileSystem.fullPath(include));
		collect(Json.parse(astText), declarations, roots, FileSystem.fullPath(header));
		declarations.sort(function(left, right) return Reflect.compare(key(left), key(right)));
		var output = new StringBuf(),
			libraryMetadata = library == null ? "" : ' @library("$library")';
		output.add('// Generated by Haxeon from $header for $target. Do not edit.\n');
		output.add('interface ${interfaceName == null ? moduleName(header) : interfaceName} @target("$target")$libraryMetadata {\n');
		for (declaration in declarations)
			emit(declaration, layouts, output);
		output.add("}\n");
		return output.toString();
	}

	static function collect(node:Dynamic, output:Array<Dynamic>, roots:Array<String>, currentFile:String):String {
		if (node == null)
			return currentFile;
		var locationFile:String = locationPath(node);
		if (locationFile != null)
			currentFile = FileSystem.fullPath(locationFile);
		Reflect.setField(node, "_hxiFile", currentFile);
		var kind:String = field(node, "kind"),
			name:String = field(node, "name");
		if (name != null
			&& !StringTools.startsWith(name, "__")
			&& (kind == "TypedefDecl" || kind == "RecordDecl" || kind == "FunctionDecl" || kind == "EnumDecl" || kind == "EnumConstantDecl")
			&& isUserDeclaration(node, roots, currentFile))
			output.push(node);
		var inner:Array<Dynamic> = field(node, "inner");
		if (inner != null && !(kind == "EnumDecl" && name != null))
			for (child in inner)
				currentFile = collect(child, output, roots, currentFile);
		return currentFile;
	}

	static function emit(node:Dynamic, layouts:Map<String, CLayout>, output:StringBuf):Void {
		var kind:String = field(node, "kind"),
			name:String = field(node, "name"),
			type:Dynamic = field(node, "type");
		switch kind {
			case "EnumDecl":
				var fixed:Dynamic = field(node, "fixedUnderlyingType"), representation = fixed == null ? "c_int" : mapType(field(fixed, "qualType")),
					values = [
						for (child in children(node))
							if (field(child, "kind") == "EnumConstantDecl") child
					];
				output.add('\tenum $name : $representation {\n');
				for (entry in values) {
					var entryName:String = field(entry, "name"),
						value = constantValue(entry);
					if (value != null)
						output.add('\t\t$entryName = $value;\n');
				}
				output.add("\t}\n");
			case "EnumConstantDecl":
				var value = projectedConstantValue(node);
				if (value != null)
					output.add('\tconst $name = $value;\n');
			case "TypedefDecl":
				var qualified:String = field(type, "qualType");
				var callback = functionPointer(qualified);
				if (callback != null) {
					output.add('\tcallback $name = fn(');
					output.add([
						for (index in 0...callback.arguments.length)
							'arg$index: ${mapType(callback.arguments[index])}'
					].join(", "));
					output.add(') -> ${mapType(callback.result)}${callback.callConvention == "cdecl" ? "" : ' @callconv("' + callback.callConvention + '")'};\n');
				} else if (!StringTools.startsWith(qualified, "struct ") && !StringTools.startsWith(qualified, "enum "))
					output.add('\ttype $name = ${mapType(qualified)};\n');
			case "RecordDecl":
				var fields:Array<Dynamic> = [for (child in children(node)) if (field(child, "kind") == "FieldDecl") child];
				if (fields.length == 0)
					return;
				var layout = layouts.get(name),
					annotation = layout == null ? "" : ' @layout(${layout.size}, ${layout.align})';
				output.add('\tstruct $name$annotation {\n');
				for (entry in fields) {
					var fieldName:String = field(entry, "name"),
						fieldType:Dynamic = field(entry, "type"),
						qualifiedType:String = field(fieldType, "qualType"),
						offset = layout == null ? null : layout.offsets.get(fieldName);
					if (StringTools.endsWith(qualifiedType, "[]"))
						throw '${declarationLocation(entry)}: unsupported flexible array field "$fieldName"';
					output.add('\t\t$fieldName: ${fieldTypeProjection(entry, qualifiedType)}${offset == null ? "" : " @offset(" + offset + ")"}${fieldPolicy(entry)};\n');
				}
				output.add("\t}\n");
			case "FunctionDecl":
				if (field(node, "variadic") == true)
					throw '${declarationLocation(node)}: unsupported variadic function "$name"';
				var parameters = [for (child in children(node)) if (field(child, "kind") == "ParmVarDecl") child];
				var rawSignature:String = field(type, "qualType"),
					callConvention = callingConvention(rawSignature),
					signature = stripCallingConvention(rawSignature),
					result = StringTools.trim(signature.substring(0, signature.indexOf("("))),
					borrowedUtf8 = hasAnnotation(node, "hxi:returns_borrowed_utf8");
				output.add('\textern fn $name(');
				output.add([
					for (parameter in parameters)
						parameterProjection(parameter)
				].join(", "));
				output.add(') -> ${borrowedUtf8 ? "utf8" : mapType(result)}${callConvention == "cdecl" ? "" : ' @callconv("' + callConvention + '")'}${borrowedUtf8 ? " @borrowed" : ""};\n');
		}
	}

	static function fieldPolicy(entry:Dynamic):String {
		var result = "";
		for (child in children(entry)) {
			if (field(child, "kind") != "AnnotateAttr")
				continue;
			var annotation = annotationSource(entry, child);
			if (annotation.indexOf("hxi:borrowed") >= 0)
				result += " @borrowed";
			if (annotation.indexOf("hxi:length_field") >= 0) {
				var direct = ~/hxi:length_field=([A-Za-z_][A-Za-z0-9_]*)/;
				if (direct.match(annotation))
					result += ' @length_field("${direct.matched(1)}")';
				else {
					var argument = expansionArgument(entry, child);
					if (argument == null)
						throw '${declarationLocation(entry)}: could not resolve borrowed-buffer length field';
					result += ' @length_field("$argument")';
				}
			}
		}
		return result;
	}

	static function fieldTypeProjection(entry:Dynamic, qualifiedType:String):String {
		for (child in children(entry)) {
			if (field(child, "kind") != "AnnotateAttr") continue;
			var annotation = annotationSource(entry, child);
			if (annotation.indexOf("hxi:nullable_utf8") >= 0) return "nullable<utf8>";
			if (annotation.indexOf("hxi:utf8") >= 0) return "utf8";
		}
		return mapType(qualifiedType);
	}

	static function parameterProjection(parameter:Dynamic):String {
		var direction = parameterDirection(parameter),
			type:Dynamic = field(parameter, "type"),
			qualified:String = field(type, "qualType");
		if (hasAnnotation(parameter, "hxi:utf8_array"))
			return '${field(parameter, "name")}: ptr<utf8>$direction';
		if (hasAnnotation(parameter, "hxi:nullable_utf8"))
			return '${field(parameter, "name")}: nullable<utf8>$direction';
		if (hasAnnotation(parameter, "hxi:utf8"))
			return '${field(parameter, "name")}: utf8$direction';
		if (StringTools.startsWith(direction, " @out_buffer")) {
			var desugared:String = field(type, "desugaredQualType");
			if (desugared != null)
				qualified = desugared;
		}
		var projected = mapType(qualified);
		if (StringTools.startsWith(direction, " @out_buffer") && !StringTools.startsWith(projected, "nullable<"))
			projected = 'nullable<$projected>';
		return '${field(parameter, "name")}: $projected$direction';
	}

	static function parameterDirection(parameter:Dynamic):String {
		var file:String = field(parameter, "_hxiFile");
		if (file == null || !FileSystem.exists(file))
			return "";
		for (child in children(parameter)) {
			if (field(child, "kind") != "AnnotateAttr")
				continue;
			var range:Dynamic = field(child, "range"),
				begin:Dynamic = field(range, "begin"),
				end:Dynamic = field(range, "end"),
				spellingBegin:Dynamic = field(begin, "spellingLoc"),
				spellingEnd:Dynamic = field(end, "spellingLoc");
			if (spellingBegin == null)
				spellingBegin = begin;
			if (spellingEnd == null)
				spellingEnd = end;
			var annotation = sourceRange(file, spellingBegin, spellingEnd);
			if (annotation.indexOf("hxi:in_array") >= 0) {
				var argument = expansionArgument(parameter, child);
				if (argument == null) throw '${declarationLocation(parameter)}: could not resolve input-array count parameter';
				return ' @in_array("$argument")';
			}
			if (annotation.indexOf("hxi:out_buffer") >= 0) {
				var direct = ~/hxi:out_buffer=([A-Za-z_][A-Za-z0-9_]*)/;
				if (direct.match(annotation))
					return ' @out_buffer("${direct.matched(1)}")';
				var expansion:Dynamic = field(begin, "expansionLoc"),
					offset:Dynamic = field(expansion, "offset"),
					expansionFile:String = field(expansion, "file");
				if (offset != null) {
					var expansionSource = File.getContent(expansionFile == null ? file : expansionFile),
						invocation = expansionSource.substring(offset, Std.int(Math.min(expansionSource.length, offset + 256))),
						argument = ~/^[A-Za-z_][A-Za-z0-9_]*\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)/;
					if (argument.match(invocation))
						return ' @out_buffer("${argument.matched(1)}")';
				}
				throw '${declarationLocation(parameter)}: could not resolve output-buffer size parameter';
			}
			if (annotation.indexOf("hxi:inout") >= 0)
				return " @inout";
			if (annotation.indexOf("hxi:out") >= 0)
				return " @out";
		}
		return "";
	}

	static function hasAnnotation(node:Dynamic, expected:String):Bool {
		var file:String = field(node, "_hxiFile");
		if (file == null || !FileSystem.exists(file))
			return false;
		for (child in children(node)) {
			if (field(child, "kind") != "AnnotateAttr")
				continue;
			var range:Dynamic = field(child, "range"),
				begin:Dynamic = field(range, "begin"),
				end:Dynamic = field(range, "end"),
				spellingBegin:Dynamic = field(begin, "spellingLoc"),
				spellingEnd:Dynamic = field(end, "spellingLoc");
			if (spellingBegin == null)
				spellingBegin = begin;
			if (spellingEnd == null)
				spellingEnd = end;
			if (sourceRange(file, spellingBegin, spellingEnd).indexOf(expected) >= 0)
				return true;
		}
		return false;
	}

	static function annotationSource(node:Dynamic, annotation:Dynamic):String {
		var range:Dynamic = field(annotation, "range"),
			begin:Dynamic = field(range, "begin"),
			end:Dynamic = field(range, "end"),
			spellingBegin:Dynamic = field(begin, "spellingLoc"),
			spellingEnd:Dynamic = field(end, "spellingLoc"),
			file:String = field(node, "_hxiFile");
		return sourceRange(file, spellingBegin == null ? begin : spellingBegin, spellingEnd == null ? end : spellingEnd);
	}

	static function expansionArgument(node:Dynamic, annotation:Dynamic):Null<String> {
		var range:Dynamic = field(annotation, "range"),
			begin:Dynamic = field(range, "begin"),
			expansion:Dynamic = field(begin, "expansionLoc"),
			offset:Dynamic = field(expansion, "offset"),
			file:String = field(expansion, "file");
		if (offset == null)
			return null;
		if (file == null)
			file = field(node, "_hxiFile");
		var source = File.getContent(file),
			invocation = source.substring(offset, Std.int(Math.min(source.length, offset + 256))),
			argument = ~/^[A-Za-z_][A-Za-z0-9_]*\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)/;
		return argument.match(invocation) ? argument.matched(1) : null;
	}

	static function sourceRange(defaultFile:String, begin:Dynamic, end:Dynamic):String {
		var start:Dynamic = field(begin, "offset"),
			finish:Dynamic = field(end, "offset"),
			tokenLength:Dynamic = field(end, "tokLen");
		if (start == null || finish == null)
			return "";
		var sourceFile:String = field(begin, "file"),
			source = File.getContent(sourceFile == null ? defaultFile : sourceFile);
		return source.substring(start, finish + (tokenLength == null ? 1 : tokenLength));
	}

	static function locationPath(node:Dynamic):Null<String> {
		var location:Dynamic = field(node, "loc"),
			range:Dynamic = field(node, "range"),
			begin:Dynamic = field(range, "begin"),
			expansion:Dynamic = field(begin, "expansionLoc"),
			path:String = field(expansion, "file");
		if (path != null)
			return path;
		path = field(location, "file");
		if (path != null)
			return path;
		var spelling:Dynamic = field(begin, "spellingLoc");
		path = field(spelling, "file");
		if (path != null)
			return path;
		return field(begin, "file");
	}

	static function functionPointer(type:String):Null<{arguments:Array<String>, result:String, callConvention:String}> {
		var callConvention = callingConvention(type);
		type = stripCallingConvention(type);
		var pattern = ~/^(.+)\(\s*\*\s*\)\s*\((.*)\)$/;
		if (!pattern.match(StringTools.trim(type)))
			return null;
		var arguments = StringTools.trim(pattern.matched(2));
		return {
			result: StringTools.trim(pattern.matched(1)),
			arguments: arguments == "" || arguments == "void" ? [] : [for (argument in arguments.split(",")) StringTools.trim(argument)],
			callConvention: callConvention
		};
	}

	static function callingConvention(type:String):String
		return type.indexOf("__attribute__((stdcall))") >= 0 || type.indexOf("__stdcall") >= 0 ? "stdcall" : "cdecl";

	static function stripCallingConvention(type:String):String {
		type = StringTools.replace(type, " __attribute__((stdcall))", "");
		type = StringTools.replace(type, " __attribute__((cdecl))", "");
		type = StringTools.replace(type, " __stdcall", "");
		type = StringTools.replace(type, " __cdecl", "");
		return StringTools.trim(type);
	}

	static function mapType(value:String):String {
		value = StringTools.trim(value);
		if (StringTools.endsWith(value, " _Nullable"))
			return 'nullable<${mapType(value.substring(0, value.length - 10))}>';
		if (StringTools.endsWith(value, " _Nonnull"))
			return mapType(value.substring(0, value.length - 9));
		if (StringTools.endsWith(value, "]")) {
			var split = value.lastIndexOf("[");
			if (split == value.length - 2)
				throw 'Unsupported flexible array type "$value"';
			return 'array<${mapType(value.substring(0, split))}, ${value.substring(split + 1, value.length - 1)}>';
		}
		if (StringTools.endsWith(value, "*")) {
			var pointee = StringTools.trim(value.substring(0, value.length - 1)),
				qualifiedPointer = ~/^(.*)\*\s*const$/;
			if (qualifiedPointer.match(pointee))
				return 'ptr<const<ptr<${mapType(qualifiedPointer.matched(1))}>>>';
			return 'ptr<${mapType(pointee)}>';
		}
		if (StringTools.startsWith(value, "const "))
			return 'const<${mapType(value.substring(6))}>';
		return switch value {
			case "hxi_utf8": "utf8";
			case "hxi_nullable_utf8": "nullable<utf8>";
			case "void": "void";
			case "char": "c_char";
			case "signed char": "c_schar";
			case "unsigned char": "c_uchar";
			case "short": "c_short";
			case "unsigned short": "c_ushort";
			case "int": "c_int";
			case "unsigned int": "c_uint";
			case "long": "c_long";
			case "unsigned long": "c_ulong";
			case "long long": "c_long_long";
			case "unsigned long long": "c_ulong_long";
			case "_Bool": "c_bool";
			case "float": "f32";
			case "double": "f64";
			case "int8_t": "i8";
			case "uint8_t": "u8";
			case "int16_t": "i16";
			case "uint16_t": "u16";
			case "int32_t": "i32";
			case "uint32_t": "u32";
			case "int64_t": "i64";
			case "uint64_t": "u64";
			case "intptr_t": "isize";
			case "uintptr_t": "usize";
			case "size_t": "usize";
			default: StringTools.startsWith(value, "struct ") ? value.substring(7) : StringTools.startsWith(value, "enum ") ? value.substring(5) : value;
		}
	}

	static function parseLayouts(text:String):Map<String, CLayout> {
		var result:Map<String, CLayout> = [],
			current:String = null,
			offsets:Map<String, Int> = [];
		for (line in text.split("\n")) {
			var record = ~/^\s*0 \| struct ([A-Za-z_][A-Za-z0-9_]*)$/;
			if (record.match(line)) {
				current = record.matched(1);
				offsets = [];
				continue;
			}
			if (current == null)
				continue;
			var fieldLine = ~/^\s*([0-9]+) \|\s+.+ ([A-Za-z_][A-Za-z0-9_]*)$/;
			if (fieldLine.match(line))
				offsets.set(fieldLine.matched(2), Std.parseInt(fieldLine.matched(1)));
			var end = ~/\[sizeof=([0-9]+), align=([0-9]+)\]/;
			if (end.match(line)) {
				result.set(current, {size: Std.parseInt(end.matched(1)), align: Std.parseInt(end.matched(2)), offsets: offsets});
				current = null;
			}
		}
		return result;
	}

	static function children(node:Dynamic):Array<Dynamic> {
		var value:Array<Dynamic> = field(node, "inner");
		return value == null ? [] : value;
	}

	static function constantValue(node:Dynamic):Null<String> {
		var value:String = field(node, "value");
		if (value != null)
			return value;
		for (child in children(node)) {
			value = constantValue(child);
			if (value != null)
				return value;
		}
		return null;
	}

	static function projectedConstantValue(node:Dynamic):Null<String> {
		var value = constantValue(node);
		if (value == null || !~/^-?[0-9]+$/.match(value))
			return value;
		var parsed = Int64.parseString(value),
			minimum = Int64.parseString("-2147483648"),
			maximum = Int64.parseString("4294967295");
		if (Int64.compare(parsed, minimum) < 0 || Int64.compare(parsed, maximum) > 0)
			throw '${declarationLocation(node)}: untyped constant "$value" does not fit a 32-bit Haxe Int';
		if (Int64.compare(parsed, Int64.parseString("2147483647")) > 0)
			parsed = Int64.sub(parsed, Int64.parseString("4294967296"));
		return Int64.toStr(parsed);
	}

	static function field(value:Dynamic, name:String):Dynamic
		return value == null ? null : Reflect.field(value, name);

	static function key(value:Dynamic):String
		return Std.string(field(value, "kind")) + ":" + Std.string(field(value, "name"));

	static function moduleName(path:String):String {
		var name = path.split("/").pop();
		return StringTools.replace(name, ".", "_");
	}

	static function isUserDeclaration(node:Dynamic, roots:Array<String>, currentFile:String):Bool {
		var location:Dynamic = field(node, "loc");
		if (location == null)
			return false;
		for (root in roots)
			if (currentFile == root || StringTools.startsWith(currentFile, root + "/"))
				return true;
		return false;
	}

	static function declarationLocation(node:Dynamic):String {
		var location:Dynamic = field(node, "loc"),
			file:String = field(node, "_hxiFile"),
			line:Dynamic = field(location, "line"),
			column:Dynamic = field(location, "col");
		if (file == null)
			file = "<header>";
		return '$file:${line == null ? "?" : line}:${column == null ? "?" : column}';
	}
}
