package compiler.ffi;

import compiler.ffi.HxiModel;

typedef HxiAuditIssue = {
	final target:String;
	final kind:String;
	final message:String;
}

typedef HxiAuditReport = {
	final header:String;
	final targets:Array<String>;
	final identical:Bool;
	final issues:Array<HxiAuditIssue>;
}

/** Audits one C header for a portable, identical ABI across Clang targets. */
class HxiAudit {
	public static function audit(header:String, targets:Array<String>, includes:Array<String>, ?profile:String, ?library:String, ?interfaceName:String):HxiAuditReport {
		if (targets.length < 2) throw "FFI audit requires at least two targets";
		if (profile != null && profile != "portable-abi64") throw 'Unknown FFI audit profile "$profile"';
		var issues:Array<HxiAuditIssue> = [], baseline:Null<String> = null, identical = true;
		for (target in targets) {
			try {
				var source = CHeaderImporter.importHeader(header, target, includes, "clang", library, interfaceName),
					model = HxiParser.parse(header + ".hxi", source),
					normalized = normalize(source, target);
				if (profile == "portable-abi64") auditPortable(model, target, issues);
				if (baseline == null) baseline = normalized; else if (baseline != normalized) {
					identical = false;
					issues.push({target: target, kind: "abi-drift", message: firstDifference(baseline, normalized)});
				}
			} catch (error:Dynamic) {
				identical = false;
				issues.push({target: target, kind: "import-error", message: Std.string(error)});
			}
		}
		return {header: header, targets: targets.copy(), identical: identical && issues.length == 0, issues: issues};
	}

	/** Imports one verified target into the canonical portable-ABI64 spelling. */
	public static function canonical(header:String, target:String, includes:Array<String>, ?library:String, ?interfaceName:String,
			?sourceLabel:String):String {
		var source = CHeaderImporter.importHeader(header, target, includes, "clang", library, interfaceName, null, sourceLabel),
			label = sourceLabel == null ? header : sourceLabel;
		return '// Generated by Haxeon from $label for portable-abi64. Do not edit.\n' + canonicalSource(source, target);
	}

	static function normalize(source:String, target:String):String {
		return stripComments(canonicalSource(source, target));
	}

	static function canonicalSource(source:String, target:String):String {
		var lines = source.split("\n");
		if (lines.length > 0 && StringTools.startsWith(lines[0], "// Generated by Haxeon")) lines.shift();
		return StringTools.replace(lines.join("\n"), '@target("$target")', '@target("portable-abi64")');
	}

	static function stripComments(source:String):String {
		var output = new StringBuf(), inBlock = false;
		for (line in source.split("\n")) {
			var value = line;
			while (true) {
				if (inBlock) {
					var blockClose = value.indexOf("*/");
					if (blockClose < 0) {
						value = "";
						break;
					}
					value = value.substr(blockClose + 2);
					inBlock = false;
				}
				var open = value.indexOf("/*");
				if (open < 0)
					break;
				var commentClose = value.indexOf("*/", open + 2);
				if (commentClose < 0) {
					value = value.substr(0, open);
					inBlock = true;
					break;
				}
				value = value.substr(0, open) + value.substr(commentClose + 2);
			}
			output.add(value);
			output.add("\n");
		}
		return output.toString();
	}

	static function firstDifference(left:String, right:String):String {
		var a = left.split("\n"), b = right.split("\n"), count = a.length < b.length ? a.length : b.length;
		for (index in 0...count) if (a[index] != b[index])
			return 'line ${index + 1} differs: "${a[index]}" versus "${b[index]}"';
		return 'declaration count differs (${a.length} versus ${b.length} lines)';
	}

	static function auditPortable(model:HxiInterface, target:String, issues:Array<HxiAuditIssue>):Void {
		if (HxiAbi.forInterface(model).pointerBits != 64)
			issues.push({target: target, kind: "non-portable-target", message: "portable-abi64 requires 64-bit pointers"});
		for (declaration in model.declarations) switch declaration {
			case Alias(name, type, _): auditType(type, target, 'alias "$name"', issues);
			case Structure(name, _, _, fields, _): for (field in fields) auditType(field.type, target, 'field "$name.${field.name}"', issues);
			case Enumeration(name, representation, _, _, _): auditType(representation, target, 'enum "$name"', issues);
			case Callback(name, parameters, result, _, _):
				for (parameter in parameters) auditType(parameter.type, target, 'callback "$name" parameter "${parameter.name}"', issues);
				auditType(result, target, 'callback "$name" result', issues);
			case Function(name, parameters, result, _, _, _, _, _):
				for (parameter in parameters) auditType(parameter.type, target, 'function "$name" parameter "${parameter.name}"', issues);
				auditType(result, target, 'function "$name" result', issues);
			case Opaque(_, _) | Constant(_, _, _):
		}
	}

	static function auditType(type:HxiType, target:String, context:String, issues:Array<HxiAuditIssue>):Void switch type {
		case Primitive("c_long" | "c_ulong" | "c_size" | "c_wchar" | "c_bool"):
			issues.push({target: target, kind: "non-portable-type", message: '$context uses ${typeName(type)}'});
		case Pointer(element) | Nullable(element) | Const(element): auditType(element, target, context, issues);
		case Array(element, _): auditType(element, target, context, issues);
		case Primitive(_) | Named(_):
	}

	static function typeName(type:HxiType):String return switch type { case Primitive(name): name; case _: "type"; };
}
