package compiler.backend.wasm;

import compiler.backend.wasm.WasmTypes.WasmInstruction;

/** UTF-16 coordinates over the UTF-8 storage shared by the Wasm string ABIs. */
class WasmUtf16Strings {
	public static function length(byteLength:Array<WasmInstruction>, byteAt:Int->Array<WasmInstruction>, allocate:Void->Int,
			destination:Int):Array<WasmInstruction> {
		var size = allocate(),
			offset = allocate(),
			count = allocate(),
			lead = allocate();
		var body = byteLength.concat([
			LocalSet(size),
			I32Const(0),
			LocalSet(offset),
			I32Const(0),
			LocalSet(count),
			Block(null),
			Loop(null),
			LocalGet(offset),
			LocalGet(size),
			I32LtS,
			I32Eqz,
			BrIf(1)
		]);
		body = body.concat(byteAt(offset)).concat([
			LocalSet(lead),
			LocalGet(lead),
			I32Const(0xc0),
			I32And,
			I32Const(0x80),
			I32Eq,
			I32Eqz,
			If(null),
			LocalGet(count),
			I32Const(1),
			I32Add,
			LocalSet(count),
			LocalGet(lead),
			I32Const(0xf0),
			I32LtS,
			I32Eqz,
			If(null),
			LocalGet(count),
			I32Const(1),
			I32Add,
			LocalSet(count),
			End,
			End,
			LocalGet(offset),
			I32Const(1),
			I32Add,
			LocalSet(offset),
			Br(0),
			End,
			End,
			LocalGet(count),
			LocalSet(destination)
		]);
		return body;
	}

	/** Finds a UTF-8 boundary; half marks the low-surrogate position within a scalar. */
	public static function byteOffset(byteLength:Array<WasmInstruction>, byteAt:Int->Array<WasmInstruction>, allocate:Void->Int, index:Int, destination:Int,
			half:Int):Array<WasmInstruction> {
		var size = allocate(),
			offset = allocate(),
			units = allocate(),
			lead = allocate(),
			width = allocate();
		var body = byteLength.concat([
			LocalSet(size),
			I32Const(0),
			LocalSet(offset),
			I32Const(0),
			LocalSet(units),
			I32Const(0),
			LocalSet(half),
			Block(null),
			Loop(null),
			LocalGet(units),
			LocalGet(index),
			I32LtS,
			I32Eqz,
			BrIf(1),
			LocalGet(offset),
			LocalGet(size),
			I32LtS,
			I32Eqz,
			BrIf(1)
		]);
		body = body.concat(byteAt(offset)).concat([
			LocalSet(lead),
			I32Const(1),
			LocalSet(width),
			LocalGet(lead),
			I32Const(0x80),
			I32LtS,
			I32Eqz,
			If(null),
			LocalGet(lead),
			I32Const(0xe0),
			I32LtS,
			If(null),
			I32Const(2),
			LocalSet(width),
			Else,
			LocalGet(lead),
			I32Const(0xf0),
			I32LtS,
			If(null),
			I32Const(3),
			LocalSet(width),
			Else,
			LocalGet(units),
			I32Const(1),
			I32Add,
			LocalGet(index),
			I32Eq,
			If(null),
			I32Const(1),
			LocalSet(half),
			Br(5),
			End,
			I32Const(4),
			LocalSet(width),
			LocalGet(units),
			I32Const(1),
			I32Add,
			LocalSet(units),
			End,
			End,
			End,
			LocalGet(units),
			I32Const(1),
			I32Add,
			LocalSet(units),
			LocalGet(offset),
			LocalGet(width),
			I32Add,
			LocalSet(offset),
			Br(0),
			End,
			End,
			LocalGet(offset),
			LocalSet(destination)
		]);
		return body;
	}

	/** Copies complete UTF-8 scalars and encodes any selected surrogate half as WTF-8. */
	public static function substring(byteLength:Array<WasmInstruction>, byteAt:Int->Array<WasmInstruction>, allocateLocal:Void->Int, startArgument:Int,
			endArgument:Int, allocateBuffer:Int->Array<WasmInstruction>, copyBytes:(Int, Int, Int) -> Array<WasmInstruction>,
			storeByte:(Int, Int) -> Array<WasmInstruction>, finish:Int->Array<WasmInstruction>):Array<WasmInstruction> {
		var size = allocateLocal(),
			start = allocateLocal(),
			end = allocateLocal(),
			first = allocateLocal(),
			last = allocateLocal(),
			firstHalf = allocateLocal(),
			lastHalf = allocateLocal(),
			copied = allocateLocal(),
			total = allocateLocal(),
			prefix = allocateLocal(),
			suffix = allocateLocal(),
			offset = allocateLocal(),
			code = allocateLocal(),
			byte = allocateLocal();
		var body = length(byteLength, byteAt, allocateLocal, size).concat([
			LocalGet(startArgument),
			LocalSet(start),
			LocalGet(endArgument),
			LocalSet(end),
			// Clamp both indexes into the string, then swap a reversed pair, as Haxe's substring does.
			LocalGet(start),
			I32Const(0),
			I32LtS,
			If(null),
			I32Const(0),
			LocalSet(start),
			End,
			LocalGet(size),
			LocalGet(start),
			I32LtS,
			If(null),
			LocalGet(size),
			LocalSet(start),
			End,
			LocalGet(end),
			I32Const(0),
			I32LtS,
			If(null),
			I32Const(0),
			LocalSet(end),
			End,
			LocalGet(size),
			LocalGet(end),
			I32LtS,
			If(null),
			LocalGet(size),
			LocalSet(end),
			End,
			LocalGet(end),
			LocalGet(start),
			I32LtS,
			If(null),
			LocalGet(start),
			LocalSet(total),
			LocalGet(end),
			LocalSet(start),
			LocalGet(total),
			LocalSet(end),
			End
		]);
		body = body.concat(byteOffset(byteLength, byteAt, allocateLocal, start, first, firstHalf));
		body = body.concat(byteOffset(byteLength, byteAt, allocateLocal, end, last, lastHalf));
		body = body.concat([
			LocalGet(start),
			LocalGet(end),
			I32Eq,
			If(null),
			I32Const(0),
			LocalSet(firstHalf),
			I32Const(0),
			LocalSet(lastHalf),
			Else,
			LocalGet(firstHalf),
			If(null),
			LocalGet(first),
			I32Const(4),
			I32Add,
			LocalSet(first),
			End,
			End,
			LocalGet(last),
			LocalGet(first),
			I32Sub,
			LocalSet(copied),
			LocalGet(firstHalf),
			I32Const(3),
			I32Mul,
			LocalSet(prefix),
			LocalGet(lastHalf),
			I32Const(3),
			I32Mul,
			LocalSet(suffix),
			LocalGet(copied),
			LocalGet(prefix),
			I32Add,
			LocalGet(suffix),
			I32Add,
			LocalSet(total)
		]);
		body = body.concat(allocateBuffer(total));
		body = body.concat(copyBytes(first, prefix, copied));
		body = body.concat([LocalGet(firstHalf), If(null)]);
		body = body.concat(charCodeAt(byteLength, byteAt, allocateLocal, start, code));
		body = body.concat([I32Const(0), LocalSet(offset)]);
		body = body.concat(writeSurrogate(code, offset, byte, storeByte)).concat([
			End,
			LocalGet(lastHalf),
			If(null),
			LocalGet(end),
			I32Const(1),
			I32Sub,
			LocalSet(offset)
		]);
		body = body.concat(charCodeAt(byteLength, byteAt, allocateLocal, offset, code));
		body = body.concat([LocalGet(prefix), LocalGet(copied), I32Add, LocalSet(offset)]);
		body = body.concat(writeSurrogate(code, offset, byte, storeByte)).concat([End]);
		return body.concat(finish(total));
	}

	static function writeSurrogate(code:Int, offset:Int, byte:Int, storeByte:(Int, Int) -> Array<WasmInstruction>):Array<WasmInstruction> {
		var body:Array<WasmInstruction> = [];
		for (shift in [12, 6, 0]) {
			body = body.concat([
				LocalGet(code),
				I32Const(shift),
				I32ShrU,
				I32Const(shift == 12 ? 15 : 63),
				I32And,
				I32Const(shift == 12 ? 0xe0 : 0x80),
				I32Or,
				LocalSet(byte)
			]);
			body = body.concat(storeByte(offset, byte));
			body = body.concat([LocalGet(offset), I32Const(1), I32Add, LocalSet(offset)]);
		}
		return body;
	}

	public static function charCodeAt(byteLength:Array<WasmInstruction>, byteAt:Int->Array<WasmInstruction>, allocate:Void->Int, index:Int,
			destination:Int):Array<WasmInstruction> {
		var size = allocate(),
			offset = allocate(),
			units = allocate(),
			scalar = allocate(),
			width = allocate(),
			next = allocate();
		var body = byteLength.concat([
			LocalSet(size),
			I32Const(0),
			LocalSet(offset),
			I32Const(0),
			LocalSet(units),
			Block(null),
			Loop(null),
			LocalGet(offset),
			LocalGet(size),
			I32LtS,
			I32Eqz,
			BrIf(1)
		]);
		body = body.concat(byteAt(offset)).concat([
			LocalSet(scalar),
			I32Const(1),
			LocalSet(width),
			LocalGet(scalar),
			I32Const(0x80),
			I32LtS,
			I32Eqz,
			If(null),
			LocalGet(scalar),
			I32Const(0xe0),
			I32LtS,
			If(null),
			I32Const(2),
			LocalSet(width),
			LocalGet(scalar),
			I32Const(0x1f),
			I32And,
			LocalSet(scalar),
			Else,
			LocalGet(scalar),
			I32Const(0xf0),
			I32LtS,
			If(null),
			I32Const(3),
			LocalSet(width),
			LocalGet(scalar),
			I32Const(0x0f),
			I32And,
			LocalSet(scalar),
			Else,
			I32Const(4),
			LocalSet(width),
			LocalGet(scalar),
			I32Const(7),
			I32And,
			LocalSet(scalar),
			End,
			End,
			I32Const(1),
			LocalSet(next),
			Block(null),
			Loop(null),
			LocalGet(next),
			LocalGet(width),
			I32LtS,
			I32Eqz,
			BrIf(1)
		]);
		var byteIndex = allocate();
		body = body.concat([
			LocalGet(offset),
			LocalGet(next),
			I32Add,
			LocalSet(byteIndex),
			LocalGet(scalar),
			I32Const(6),
			I32Shl
		]);
		body = body.concat(byteAt(byteIndex)).concat([
			I32Const(0x3f),
			I32And,
			I32Or,
			LocalSet(scalar),
			LocalGet(next),
			I32Const(1),
			I32Add,
			LocalSet(next),
			Br(0),
			End,
			End,
			End,
			LocalGet(units),
			LocalGet(index),
			I32Eq,
			If(null),
			LocalGet(scalar),
			I32Const(0xffff),
			I32LeS,
			I32Eqz,
			If(I32),
			LocalGet(scalar),
			I32Const(0x10000),
			I32Sub,
			I32Const(10),
			I32ShrU,
			I32Const(0xd800),
			I32Add,
			Else,
			LocalGet(scalar),
			End,
			LocalSet(destination),
			Br(2),
			End,
			LocalGet(scalar),
			I32Const(0xffff),
			I32LeS,
			I32Eqz,
			If(null),
			LocalGet(units),
			I32Const(1),
			I32Add,
			LocalSet(units),
			LocalGet(units),
			LocalGet(index),
			I32Eq,
			If(null),
			LocalGet(scalar),
			I32Const(0x10000),
			I32Sub,
			I32Const(0x3ff),
			I32And,
			I32Const(0xdc00),
			I32Add,
			LocalSet(destination),
			Br(3),
			End,
			End,
			LocalGet(units),
			I32Const(1),
			I32Add,
			LocalSet(units),
			LocalGet(offset),
			LocalGet(width),
			I32Add,
			LocalSet(offset),
			Br(0),
			End,
			Unreachable,
			End
		]);
		return body;
	}
}
