package compiler.backend.wasm;

import compiler.backend.wasm.WasmTypes.WasmInstruction;
import compiler.backend.wasm.WasmTypes.WasmValueType;
import compiler.backend.wasm.WasmModule.WasmFunction;
import compiler.backend.wasm.WasmModule.WasmModule;
import compiler.backend.wasm.WasmFunctionBuilder.WasmFunctionBuilder;
import compiler.backend.wasm.WasmFunctionBuilder.WasmLocalRef;

private typedef FloatStringLocals = {
	final value:WasmLocalRef;
	final decimalExponent:WasmLocalRef;
	final significand:WasmLocalRef;
	final decimalKind:WasmLocalRef;
	final significandWork:WasmLocalRef;
	final significandDigitCount:WasmLocalRef;
	final isNegative:WasmLocalRef;
	final decimalPointPosition:WasmLocalRef;
	final useScientificNotation:WasmLocalRef;
	final scientificExponent:WasmLocalRef;
	final exponentMagnitude:WasmLocalRef;
	final exponentDigitCount:WasmLocalRef;
	final outputLength:WasmLocalRef;
	final outputString:WasmLocalRef;
	final digitIndex:WasmLocalRef;
	final digitValue:WasmLocalRef;
	final significandDigitOffset:WasmLocalRef;
	final outputOffset:WasmLocalRef;
	final exponentStart:WasmLocalRef;
	final numericWork:WasmLocalRef;
	final exponentDigitIndex:WasmLocalRef;
}

/** Ryū binary64 conversion and Haxeon string rendering for linear-memory Wasm. */
class WasmNumericString {
	static inline final STRING_DATA_OFFSET = WasmLayout.STRING_DATA_OFFSET;
	static inline final STRING_LENGTH_OFFSET = WasmLayout.STRING_LENGTH_OFFSET;
	static inline final ARRAY_CAPACITY_OFFSET = WasmLayout.ARRAY_CAPACITY_OFFSET;

	public static function addFloatToString(module:WasmModule, name:String, allocator:Int, bytesTypeId:Int, tableBase:Int, nanString:Int, infinityString:Int,
			negativeInfinityString:Int, zeroString:Int):Int {
		var umul = addUnsignedMultiply128(module, '__${name}_umul128'),
			mulShift = addMultiplyShift(module, '__${name}_mul_shift', umul),
			mulShiftAll = addMultiplyShiftAll(module, '__${name}_mul_shift_all', mulShift),
			pow5Factor = addPow5Factor(module, '__${name}_pow5_factor');
		var decimal = addDoubleToDecimal(module, '__${name}_decimal', tableBase, tableBase + WasmRyuTables.INVERSE_ENTRIES * 16, mulShiftAll, pow5Factor),
			builder = new WasmFunctionBuilder(name, {parameters: [F64], results: [I32]}),
			value = builder.parameter("value", 0),
			decimalExponent = builder.local("decimalExponent", I32),
			significand = builder.local("significand", I64),
			decimalKind = builder.local("decimalKind", I32),
			significandWork = builder.local("significandWork", I64),
			significandDigitCount = builder.local("significandDigitCount", I32),
			isNegative = builder.local("isNegative", I32),
			decimalPointPosition = builder.local("decimalPointPosition", I32),
			useScientificNotation = builder.local("useScientificNotation", I32),
			scientificExponent = builder.local("scientificExponent", I32),
			exponentMagnitude = builder.local("exponentMagnitude", I32),
			exponentDigitCount = builder.local("exponentDigitCount", I32),
			outputLength = builder.local("outputLength", I32),
			outputString = builder.local("outputString", I32),
			digitIndex = builder.local("digitIndex", I32),
			digitValue = builder.local("digitValue", I32),
			significandDigitOffset = builder.local("significandDigitOffset", I32),
			outputOffset = builder.local("outputOffset", I32),
			exponentStart = builder.local("exponentStart", I32),
			numericWork = builder.local("numericWork", I32),
			exponentDigitIndex = builder.local("exponentDigitIndex", I32);
		var locals:FloatStringLocals = {
			value: value,
			decimalExponent: decimalExponent,
			significand: significand,
			decimalKind: decimalKind,
			significandWork: significandWork,
			significandDigitCount: significandDigitCount,
			isNegative: isNegative,
			decimalPointPosition: decimalPointPosition,
			useScientificNotation: useScientificNotation,
			scientificExponent: scientificExponent,
			exponentMagnitude: exponentMagnitude,
			exponentDigitCount: exponentDigitCount,
			outputLength: outputLength,
			outputString: outputString,
			digitIndex: digitIndex,
			digitValue: digitValue,
			significandDigitOffset: significandDigitOffset,
			outputOffset: outputOffset,
			exponentStart: exponentStart,
			numericWork: numericWork,
			exponentDigitIndex: exponentDigitIndex
		};

		builder.emitAll([
			LocalGet(locals.value),
			I32Const(tableBase),
			I32Const(tableBase + WasmRyuTables.INVERSE_ENTRIES * 16),
			Call(decimal),
			LocalSet(locals.decimalKind),
			LocalSet(locals.decimalExponent),
			LocalSet(locals.significand)
		]);
		appendSpecialValueReturns(builder, locals, nanString, infinityString, negativeInfinityString, zeroString);
		appendSignificandShape(builder, locals);
		appendOutputLayout(builder, locals);
		appendOutputStringAllocation(builder, locals, allocator, bytesTypeId);
		appendSignificandDigits(builder, locals);
		builder.localGet(locals.useScientificNotation);
		builder.ifElse(
			function(builder) appendScientificBranch(builder, locals),
			function(builder) appendFixedBranch(builder, locals)
		);
		builder.localGet(locals.outputString);
		builder.return_();
		return module.addFunction(builder.finish());
	}

	static function appendSpecialValueReturns(
			builder:WasmFunctionBuilder, locals:FloatStringLocals, nanString:Int, infinityString:Int, negativeInfinityString:Int, zeroString:Int):Void {
		builder.emitAll([
			LocalGet(locals.decimalKind),
			I32Const(2),
			I32Eq,
			If(null),
			I32Const(nanString),
			Return,
			End,
			LocalGet(locals.decimalKind),
			I32Const(3),
			I32Eq,
			If(null),
			I32Const(infinityString),
			Return,
			End,
			LocalGet(locals.decimalKind),
			I32Const(4),
			I32Eq,
			If(null),
			I32Const(negativeInfinityString),
			Return,
			End,
			LocalGet(locals.decimalKind),
			I32Const(5),
			I32Eq,
			If(null),
			I32Const(zeroString),
			Return,
			End,
		]);
	}

	static function appendSignificandShape(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			LocalGet(locals.decimalKind),
			I32Const(1),
			I32Eq,
			If(I32),
			I32Const(1),
			Else,
			I32Const(0),
			End,
			LocalSet(locals.isNegative),
			LocalGet(locals.significand),
			LocalSet(locals.significandWork),
			I32Const(1),
			LocalSet(locals.significandDigitCount),
			Block(null),
			Loop(null),
			LocalGet(locals.significandWork),
			I64Const(10),
			I64LtS,
			BrIf(1),
			LocalGet(locals.significandWork),
			I64Const(10),
			I64DivS,
			LocalSet(locals.significandWork),
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32Add,
			LocalSet(locals.significandDigitCount),
			Br(0),
			End,
			End,
			LocalGet(locals.significandDigitCount),
			LocalGet(locals.decimalExponent),
			I32Add,
			LocalSet(locals.decimalPointPosition),
		]);
	}

	static function appendOutputLayout(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			// Haxe-style general number rendering: fixed in (-6, 21], scientific otherwise.
			I32Const(0),
			LocalSet(locals.useScientificNotation),
			LocalGet(locals.decimalPointPosition),
			I32Const(21),
			I32LeS,
			I32Eqz,
			If(null),
			I32Const(1),
			LocalSet(locals.useScientificNotation),
			End,
			LocalGet(locals.decimalPointPosition),
			I32Const(-6),
			I32LeS,
			If(null),
			I32Const(1),
			LocalSet(locals.useScientificNotation),
			End,
			LocalGet(locals.useScientificNotation),
			If(null),
			LocalGet(locals.decimalPointPosition),
			I32Const(1),
			I32Sub,
			LocalSet(locals.scientificExponent),
			LocalGet(locals.scientificExponent),
			I32Const(0),
			I32LtS,
			If(I32),
			I32Const(0),
			LocalGet(locals.scientificExponent),
			I32Sub,
			Else,
			LocalGet(locals.scientificExponent),
			End,
			LocalSet(locals.exponentMagnitude),
			LocalGet(locals.exponentMagnitude),
			LocalSet(locals.numericWork),
			I32Const(1),
			LocalSet(locals.exponentDigitCount),
			Block(null),
			Loop(null),
			LocalGet(locals.numericWork),
			I32Const(10),
			I32LtS,
			BrIf(1),
			LocalGet(locals.numericWork),
			I32Const(10),
			I32DivS,
			LocalSet(locals.numericWork),
			LocalGet(locals.exponentDigitCount),
			I32Const(1),
			I32Add,
			LocalSet(locals.exponentDigitCount),
			Br(0),
			End,
			End,
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitCount),
			I32Add,
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32LeS,
			If(I32),
			I32Const(0),
			Else,
			I32Const(1),
			End,
			I32Add,
			I32Const(2),
			I32Add,
			LocalGet(locals.exponentDigitCount),
			I32Add,
			LocalSet(locals.outputLength),
			Else,
			LocalGet(locals.decimalPointPosition),
			I32Const(0),
			I32LeS,
			If(null),
			LocalGet(locals.isNegative),
			I32Const(2),
			I32Add,
			LocalGet(locals.decimalPointPosition),
			I32Sub,
			LocalGet(locals.significandDigitCount),
			I32Add,
			LocalSet(locals.outputLength),
			Else,
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitCount),
			I32LtS,
			If(null),
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitCount),
			I32Add,
			I32Const(1),
			I32Add,
			LocalSet(locals.outputLength),
			Else,
			LocalGet(locals.isNegative),
			LocalGet(locals.decimalPointPosition),
			I32Add,
			LocalSet(locals.outputLength),
			End,
			End,
			End,
		]);
	}

	static function appendOutputStringAllocation(builder:WasmFunctionBuilder, locals:FloatStringLocals, allocator:Int, bytesTypeId:Int):Void {
		builder.emitAll([
			LocalGet(locals.outputLength),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			Call(allocator),
			LocalSet(locals.outputString),
			LocalGet(locals.outputString),
			I32Const(bytesTypeId),
			I32Store(0),
			LocalGet(locals.outputString),
			LocalGet(locals.outputLength),
			I32Store(STRING_LENGTH_OFFSET),
			LocalGet(locals.outputString),
			LocalGet(locals.outputLength),
			I32Store(ARRAY_CAPACITY_OFFSET),
			LocalGet(locals.decimalKind),
			I32Const(1),
			I32Eq,
			If(null),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			I32Const(45),
			I32Store8(0),
			End,
		]);
	}

	static function appendSignificandDigits(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			// Store coefficient digits directly at their final output positions, right-to-left.
			LocalGet(locals.significand),
			LocalSet(locals.significandWork),
			I32Const(0),
			LocalSet(locals.digitIndex),
			Block(null),
			Loop(null),
			LocalGet(locals.significandDigitCount),
			LocalGet(locals.digitIndex),
			I32LeS,
			BrIf(1),
			LocalGet(locals.significandWork),
			I64Const(10),
			I64RemS,
			I32WrapI64,
			LocalSet(locals.digitValue),
			LocalGet(locals.significandWork),
			I64Const(10),
			I64DivS,
			LocalSet(locals.significandWork),
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32Sub,
			LocalGet(locals.digitIndex),
			I32Sub,
			LocalSet(locals.significandDigitOffset),
			LocalGet(locals.useScientificNotation),
			If(I32),
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitOffset),
			I32Eqz,
			If(I32),
			I32Const(0),
			Else,
			LocalGet(locals.significandDigitOffset),
			I32Const(1),
			I32Add,
			End,
			I32Add,
			Else,
			LocalGet(locals.decimalPointPosition),
			I32Const(0),
			I32LeS,
			If(I32),
			LocalGet(locals.isNegative),
			I32Const(2),
			I32Add,
			LocalGet(locals.decimalPointPosition),
			I32Sub,
			LocalGet(locals.significandDigitOffset),
			I32Add,
			Else,
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitCount),
			I32LeS,
			If(I32),
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitOffset),
			I32Add,
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitOffset),
			I32LeS,
			If(I32),
			I32Const(1),
			Else,
			I32Const(0),
			End,
			I32Add,
			Else,
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitOffset),
			I32Add,
			End,
			End,
			End,
			LocalSet(locals.outputOffset),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.outputOffset),
			I32Add,
			LocalGet(locals.digitValue),
			I32Const(48),
			I32Add,
			I32Store8(0),
			LocalGet(locals.digitIndex),
			I32Const(1),
			I32Add,
			LocalSet(locals.digitIndex),
			Br(0),
			End,
			End,
		]);
	}

	static function appendScientificBranch(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32LeS,
			I32Eqz,
			If(null),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			I32Add,
			I32Const(1),
			I32Add,
			I32Const(46),
			I32Store8(0),
			End,
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitCount),
			I32Add,
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32LeS,
			If(I32),
			I32Const(0),
			Else,
			I32Const(1),
			End,
			I32Add,
			LocalSet(locals.exponentStart),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.exponentStart),
			I32Add,
			I32Const(101),
			I32Store8(0),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.exponentStart),
			I32Const(1),
			I32Add,
			I32Add,
			LocalGet(locals.scientificExponent),
			I32Const(0),
			I32LtS,
			If(I32),
			I32Const(45),
			Else,
			I32Const(43),
			End,
			I32Store8(0),
			LocalGet(locals.exponentStart),
			I32Const(2),
			I32Add,
			LocalSet(locals.exponentStart),
			LocalGet(locals.exponentDigitCount),
			LocalSet(locals.exponentDigitIndex),
			I32Const(0),
			LocalSet(locals.digitIndex),
			LocalGet(locals.exponentMagnitude),
			LocalSet(locals.numericWork),
			Block(null),
			Loop(null),
			LocalGet(locals.exponentDigitIndex),
			LocalGet(locals.digitIndex),
			I32LeS,
			BrIf(1),
			LocalGet(locals.numericWork),
			I32Const(10),
			I32RemS,
			I32Const(48),
			I32Add,
			LocalSet(locals.digitValue),
			LocalGet(locals.numericWork),
			I32Const(10),
			I32DivS,
			LocalSet(locals.numericWork),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.exponentStart),
			LocalGet(locals.exponentDigitIndex),
			I32Add,
			LocalGet(locals.digitIndex),
			I32Sub,
			I32Const(1),
			I32Sub,
			I32Add,
			LocalGet(locals.digitValue),
			I32Store8(0),
			LocalGet(locals.digitIndex),
			I32Const(1),
			I32Add,
			LocalSet(locals.digitIndex),
			Br(0),
			End,
			End,
		]);
	}

	static function appendFixedBranch(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			LocalGet(locals.decimalPointPosition),
			I32Const(0),
			I32LeS,
			If(null),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			I32Add,
			I32Const(48),
			I32Store8(0),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			I32Const(1),
			I32Add,
			I32Add,
			I32Const(46),
			I32Store8(0),
			I32Const(0),
			LocalSet(locals.digitIndex),
			I32Const(0),
			LocalGet(locals.decimalPointPosition),
			I32Sub,
			LocalSet(locals.outputOffset),
			Block(null),
			Loop(null),
			LocalGet(locals.outputOffset),
			LocalGet(locals.digitIndex),
			I32LeS,
			BrIf(1),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			I32Const(2),
			I32Add,
			LocalGet(locals.digitIndex),
			I32Add,
			I32Add,
			I32Const(48),
			I32Store8(0),
			LocalGet(locals.digitIndex),
			I32Const(1),
			I32Add,
			LocalSet(locals.digitIndex),
			Br(0),
			End,
			End,
			Else,
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitCount),
			I32LtS,
			If(null),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			LocalGet(locals.decimalPointPosition),
			I32Add,
			I32Add,
			I32Const(46),
			I32Store8(0),
			Else,
			I32Const(0),
			LocalSet(locals.digitIndex),
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitCount),
			I32Sub,
			LocalSet(locals.outputOffset),
			Block(null),
			Loop(null),
			LocalGet(locals.outputOffset),
			LocalGet(locals.digitIndex),
			I32LeS,
			BrIf(1),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitCount),
			I32Add,
			LocalGet(locals.digitIndex),
			I32Add,
			I32Add,
			I32Const(48),
			I32Store8(0),
			LocalGet(locals.digitIndex),
			I32Const(1),
			I32Add,
			LocalSet(locals.digitIndex),
			Br(0),
			End,
			End,
			End,
			End,
		]);
	}

	static function addUnsignedMultiply128(module:WasmModule, name:String):Int {
		var body:Array<WasmInstruction> = [
			LocalGet(0),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(2),
			LocalGet(0),
			I64Const(32),
			I64ShrU,
			LocalSet(3),
			LocalGet(1),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(4),
			LocalGet(1),
			I64Const(32),
			I64ShrU,
			LocalSet(5),
			LocalGet(2),
			LocalGet(4),
			I64Mul,
			LocalSet(6),
			LocalGet(2),
			LocalGet(5),
			I64Mul,
			LocalSet(7),
			LocalGet(3),
			LocalGet(4),
			I64Mul,
			LocalSet(8),
			LocalGet(3),
			LocalGet(5),
			I64Mul,
			LocalSet(9),
			LocalGet(6),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(10),
			LocalGet(6),
			I64Const(32),
			I64ShrU,
			LocalSet(11),
			LocalGet(8),
			LocalGet(11),
			I64Add,
			LocalSet(12),
			LocalGet(12),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(13),
			LocalGet(12),
			I64Const(32),
			I64ShrU,
			LocalSet(14),
			LocalGet(7),
			LocalGet(13),
			I64Add,
			LocalSet(15),
			LocalGet(15),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(16),
			LocalGet(15),
			I64Const(32),
			I64ShrU,
			LocalSet(17),
			LocalGet(16),
			I64Const(32),
			I64Shl,
			LocalGet(10),
			I64Or,
			LocalSet(18),
			LocalGet(9),
			LocalGet(14),
			I64Add,
			LocalGet(17),
			I64Add,
			LocalSet(19),
			LocalGet(18),
			LocalGet(19),
			Return
		];
		return module.addFunction(new WasmFunction(name, {parameters: [I64, I64], results: [I64, I64]}, [
			for (_ in 0...18)
				{type: I64}
		], body));
	}

	static function addMultiplyShift(module:WasmModule, name:String, umul:Int):Int {
		var body:Array<WasmInstruction> = [
			LocalGet(0),
			LocalGet(1),
			I64Load(8),
			Call(umul),
			LocalSet(4),
			LocalSet(3),
			LocalGet(0),
			LocalGet(1),
			I64Load(0),
			Call(umul),
			LocalSet(5),
			Drop,
			LocalGet(5),
			LocalGet(3),
			I64Add,
			LocalSet(6),
			LocalGet(6),
			LocalGet(5),
			I64LtU,
			LocalSet(7),
			LocalGet(4),
			LocalGet(7),
			I64ExtendI32U,
			I64Add,
			LocalSet(4),
			LocalGet(2),
			I32Const(64),
			I32Sub,
			LocalSet(8),
			LocalGet(4),
			I32Const(64),
			LocalGet(8),
			I32Sub,
			I64ExtendI32U,
			I64Shl,
			LocalGet(6),
			LocalGet(8),
			I64ExtendI32U,
			I64ShrU,
			I64Or,
			Return
		];
		return module.addFunction(new WasmFunction(name, {parameters: [I64, I32, I32], results: [I64]},
			[{type: I64}, {type: I64}, {type: I64}, {type: I64}, {type: I32}, {type: I32}], body));
	}

	static function addMultiplyShiftAll(module:WasmModule, name:String, mulShift:Int):Int {
		var body:Array<WasmInstruction> = [
			LocalGet(0),
			I64Const(2),
			I64Shl,
			LocalGet(1),
			LocalGet(2),
			Call(mulShift),
			LocalGet(0),
			I64Const(2),
			I64Shl,
			I64Const(2),
			I64Add,
			LocalGet(1),
			LocalGet(2),
			Call(mulShift),
			LocalGet(0),
			I64Const(2),
			I64Shl,
			I64Const(1),
			I64Sub,
			LocalGet(3),
			I64ExtendI32U,
			I64Sub,
			LocalGet(1),
			LocalGet(2),
			Call(mulShift),
			Return
		];
		return module.addFunction(new WasmFunction(name, {parameters: [I64, I32, I32, I32], results: [I64, I64, I64]}, [], body));
	}

	static function addPow5Factor(module:WasmModule, name:String):Int {
		var body:Array<WasmInstruction> = [
			I32Const(0),
			LocalSet(2),
			Block(null),
			Loop(null),
			LocalGet(0),
			I64Const(5),
			I64RemS,
			I64Eqz,
			I32Eqz,
			BrIf(1),
			LocalGet(0),
			I64Const(5),
			I64DivS,
			LocalSet(0),
			LocalGet(2),
			I32Const(1),
			I32Add,
			LocalSet(2),
			Br(0),
			End,
			End,
			LocalGet(2),
			Return
		];
		return module.addFunction(new WasmFunction(name, {parameters: [I64], results: [I32]}, [{type: I32}], body));
	}

	static function addDoubleToDecimal(module:WasmModule, name:String, inverseTable:Int, powerTable:Int, mulShiftAll:Int, pow5Factor:Int):Int {
		var body:Array<WasmInstruction> = [];
		append(body, [
			LocalGet(0),
			I64ReinterpretF64,
			LocalSet(3),
			LocalGet(3),
			I64Const(63),
			I64ShrU,
			I32WrapI64,
			LocalSet(4),
			I64Const(-1),
			I64Const(12),
			I64ShrU,
			LocalGet(3),
			I64And,
			LocalSet(5),
			LocalGet(3),
			I64Const(52),
			I64ShrU,
			I64Const(2047),
			I64And,
			I32WrapI64,
			LocalSet(6),
			// NaN has a non-zero payload; infinities have a zero payload.
			LocalGet(6),
			I32Const(2047),
			I32Eq,
			If(null),
			LocalGet(5),
			I64Eqz,
			I32Eqz,
			If(null),
			I64Const(0),
			I32Const(0),
			I32Const(2),
			Return,
			End,
			I64Const(0),
			I32Const(0),
			LocalGet(4),
			If(I32),
			I32Const(4),
			Else,
			I32Const(3),
			End,
			Return,
			End,
			LocalGet(6),
			I32Eqz,
			LocalGet(5),
			I64Eqz,
			I32And,
			If(null),
			I64Const(0),
			I32Const(0),
			I32Const(5),
			Return,
			End,
			// Decode the finite IEEE-754 value into m2 * 2^e2.
			LocalGet(6),
			I32Eqz,
			If(null),
			I32Const(-1076),
			LocalSet(8),
			LocalGet(5),
			LocalSet(7),
			Else,
			LocalGet(6),
			I32Const(1077),
			I32Sub,
			LocalSet(8),
			LocalGet(5),
			I64Const(1),
			I64Const(52),
			I64Shl,
			I64Add,
			LocalSet(7),
			End,
			LocalGet(7),
			I64Const(1),
			I64And,
			I64Eqz,
			LocalSet(9),
			LocalGet(5),
			I64Eqz,
			I32Eqz,
			LocalGet(6),
			I32Const(1),
			I32LeS,
			I32Or,
			LocalSet(10),
			LocalGet(7),
			I64Const(2),
			I64Shl,
			LocalSet(11),
			I32Const(0),
			LocalSet(21),
			I32Const(0),
			LocalSet(22),
			LocalGet(8),
			I32Const(0),
			I32LtS,
			If(null),
			// e2 < 0: multiply by a split power of five.
			I32Const(0),
			LocalGet(8),
			I32Sub,
			LocalSet(23),
			LocalGet(23),
			I32Const(732923),
			I32Mul,
			I32Const(20),
			I32ShrU,
			LocalSet(12),
			LocalGet(23),
			I32Const(1),
			I32LeS,
			If(null),
			Else,
			LocalGet(12),
			I32Const(1),
			I32Sub,
			LocalSet(12),
			End,
			LocalGet(12),
			LocalGet(8),
			I32Add,
			LocalSet(13),
			LocalGet(23),
			LocalGet(12),
			I32Sub,
			LocalSet(14),
			LocalGet(14),
			I32Const(1217359),
			I32Mul,
			I32Const(19),
			I32ShrU,
			I32Const(1),
			I32Add,
			I32Const(125),
			I32Sub,
			LocalSet(15),
			LocalGet(12),
			LocalGet(15),
			I32Sub,
			LocalSet(16),
			LocalGet(2),
			LocalGet(14),
			I32Const(4),
			I32Shl,
			I32Add,
			LocalSet(17),
			LocalGet(7),
			LocalGet(17),
			LocalGet(16),
			LocalGet(10),
			Call(mulShiftAll),
			LocalSet(20),
			LocalSet(19),
			LocalSet(18),
			LocalGet(12),
			I32Const(1),
			I32LeS,
			If(null),
			I32Const(1),
			LocalSet(22),
			LocalGet(9),
			If(null),
			LocalGet(10),
			I32Const(1),
			I32Eq,
			LocalSet(21),
			Else,
			LocalGet(19),
			I64Const(1),
			I64Sub,
			LocalSet(19),
			End,
			Else,
			I32Const(63),
			LocalGet(12),
			I32LtS,
			If(null),
			I64Const(1),
			LocalGet(12),
			I64ExtendI32U,
			I64Shl,
			I64Const(1),
			I64Sub,
			LocalGet(11),
			I64And,
			I64Eqz,
			LocalSet(22),
			End,
			End,
			Else,
			// e2 >= 0: divide by a split inverse power of five.
			LocalGet(8),
			I32Const(78913),
			I32Mul,
			I32Const(18),
			I32ShrU,
			LocalSet(12),
			LocalGet(8),
			I32Const(3),
			I32LeS,
			If(null),
			Else,
			LocalGet(12),
			I32Const(1),
			I32Sub,
			LocalSet(12),
			End,
			LocalGet(12),
			LocalSet(13),
			LocalGet(12),
			I32Const(1217359),
			I32Mul,
			I32Const(19),
			I32ShrU,
			I32Const(125),
			I32Add,
			LocalSet(15),
			I32Const(0),
			LocalGet(8),
			I32Sub,
			LocalGet(12),
			I32Add,
			LocalGet(15),
			I32Add,
			LocalSet(16),
			LocalGet(1),
			LocalGet(12),
			I32Const(4),
			I32Shl,
			I32Add,
			LocalSet(17),
			LocalGet(7),
			LocalGet(17),
			LocalGet(16),
			LocalGet(10),
			Call(mulShiftAll),
			LocalSet(20),
			LocalSet(19),
			LocalSet(18),
			LocalGet(12),
			I32Const(21),
			I32LeS,
			If(null),
			LocalGet(11),
			I64Const(5),
			I64RemS,
			I64Eqz,
			If(null),
			LocalGet(11),
			Call(pow5Factor),
			LocalSet(23),
			LocalGet(12),
			LocalGet(23),
			I32LeS,
			LocalSet(22),
			Else,
			LocalGet(9),
			If(null),
			LocalGet(11),
			I64Const(1),
			I64Sub,
			LocalGet(10),
			I64ExtendI32U,
			I64Sub,
			Call(pow5Factor),
			LocalSet(23),
			LocalGet(12),
			LocalGet(23),
			I32LeS,
			LocalSet(21),
			Else,
			LocalGet(11),
			I64Const(2),
			I64Add,
			Call(pow5Factor),
			LocalSet(23),
			LocalGet(19),
			LocalGet(12),
			LocalGet(23),
			I32LeS,
			If(I32),
			I32Const(1),
			Else,
			I32Const(0),
			End,
			I64ExtendI32U,
			I64Sub,
			LocalSet(19),
			End,
			End,
			End,
			End,
			// Remove digits while the rounded interval still contains a representation.
			I32Const(0),
			LocalSet(25),
			I32Const(0),
			LocalSet(26),
			LocalGet(21),
			LocalGet(22),
			I32Or,
			If(null),
			Block(null),
			Loop(null),
			LocalGet(19),
			I64Const(10),
			I64DivS,
			LocalSet(28),
			LocalGet(20),
			I64Const(10),
			I64DivS,
			LocalSet(29),
			LocalGet(28),
			LocalGet(29),
			I64LeS,
			BrIf(1),
			LocalGet(20),
			LocalGet(29),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(30),
			LocalGet(18),
			I64Const(10),
			I64DivS,
			LocalSet(27),
			LocalGet(18),
			LocalGet(27),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(26),
			LocalGet(21),
			LocalGet(30),
			I32Eqz,
			I32And,
			LocalSet(21),
			LocalGet(22),
			LocalGet(26),
			I32Eqz,
			I32And,
			LocalSet(22),
			LocalGet(27),
			LocalSet(18),
			LocalGet(28),
			LocalSet(19),
			LocalGet(29),
			LocalSet(20),
			LocalGet(25),
			I32Const(1),
			I32Add,
			LocalSet(25),
			Br(0),
			End,
			End,
			LocalGet(21),
			If(null),
			Block(null),
			Loop(null),
			LocalGet(20),
			I64Const(10),
			I64DivS,
			LocalSet(29),
			LocalGet(20),
			LocalGet(29),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			I32Eqz,
			I32Eqz,
			BrIf(1),
			LocalGet(18),
			I64Const(10),
			I64DivS,
			LocalSet(28),
			LocalGet(18),
			LocalGet(28),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(26),
			LocalGet(22),
			LocalGet(26),
			I32Eqz,
			I32And,
			LocalSet(22),
			LocalGet(19),
			I64Const(10),
			I64DivS,
			LocalSet(19),
			LocalGet(28),
			LocalSet(18),
			LocalGet(29),
			LocalSet(20),
			LocalGet(25),
			I32Const(1),
			I32Add,
			LocalSet(25),
			Br(0),
			End,
			End,
			End,
			LocalGet(22),
			If(null),
			LocalGet(26),
			I32Const(5),
			I32Eq,
			LocalGet(18),
			I64Const(1),
			I64And,
			I64Eqz,
			I32And,
			If(null),
			I32Const(4),
			LocalSet(26),
			End,
			End,
			LocalGet(18),
			LocalGet(18),
			LocalGet(20),
			I64Eq,
			LocalGet(9),
			I32Eqz,
			LocalGet(21),
			I32Eqz,
			I32Or,
			I32And,
			I32Const(5),
			LocalGet(26),
			I32LeS,
			I32Or,
			I64ExtendI32U,
			I64Add,
			LocalSet(27),
			Else,
			I32Const(0),
			LocalSet(23),
			LocalGet(19),
			I64Const(100),
			I64DivS,
			LocalSet(28),
			LocalGet(20),
			I64Const(100),
			I64DivS,
			LocalSet(29),
			LocalGet(29),
			LocalGet(28),
			I64LtS,
			If(null),
			LocalGet(18),
			I64Const(100),
			I64DivS,
			LocalSet(27),
			LocalGet(18),
			LocalGet(27),
			I64Const(100),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(30),
			I32Const(50),
			LocalGet(30),
			I32LeS,
			LocalSet(23),
			LocalGet(27),
			LocalSet(18),
			LocalGet(28),
			LocalSet(19),
			LocalGet(29),
			LocalSet(20),
			LocalGet(25),
			I32Const(2),
			I32Add,
			LocalSet(25),
			End,
			Block(null),
			Loop(null),
			LocalGet(19),
			I64Const(10),
			I64DivS,
			LocalSet(28),
			LocalGet(20),
			I64Const(10),
			I64DivS,
			LocalSet(29),
			LocalGet(28),
			LocalGet(29),
			I64LeS,
			BrIf(1),
			LocalGet(18),
			I64Const(10),
			I64DivS,
			LocalSet(27),
			LocalGet(18),
			LocalGet(27),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(30),
			I32Const(5),
			LocalGet(30),
			I32LeS,
			LocalSet(23),
			LocalGet(27),
			LocalSet(18),
			LocalGet(28),
			LocalSet(19),
			LocalGet(29),
			LocalSet(20),
			LocalGet(25),
			I32Const(1),
			I32Add,
			LocalSet(25),
			Br(0),
			End,
			End,
			LocalGet(18),
			LocalGet(18),
			LocalGet(20),
			I64Eq,
			LocalGet(23),
			I32Or,
			I64ExtendI32U,
			I64Add,
			LocalSet(27),
			End,
			LocalGet(27),
			LocalGet(13),
			LocalGet(25),
			I32Add,
			LocalGet(4),
			Return
		]);
		var locals:Array<WasmValueType> = [
			I64, I32, I64, I32, I64, I32, I32, I32, I64, I32, I32, I32, I32, I32, I32, I64, I64, I64, I32, I32, I32, I32, I32, I32, I64, I64, I64, I32, I32
		];
		return module.addFunction(new WasmFunction(name, {parameters: [F64, I32, I32], results: [I64, I32, I32]}, [for (type in locals) {type: type}], body));
	}

	static function append(body:Array<WasmInstruction>, instructions:Array<WasmInstruction>):Void
		for (instruction in instructions)
			body.push(instruction);
}
