package compiler.backend.wasm;

import compiler.backend.wasm.WasmTypes.WasmInstruction;
import compiler.backend.wasm.WasmTypes.WasmValueType;
import compiler.backend.wasm.WasmModule.WasmFunction;
import compiler.backend.wasm.WasmModule.WasmModule;
import compiler.backend.wasm.WasmFunctionBuilder.WasmFunctionBuilder;
import compiler.backend.wasm.WasmFunctionBuilder.WasmLocalRef;

private typedef FloatStringLocals = {
	final value:WasmLocalRef;
	final decimalExponent:WasmLocalRef;
	final significand:WasmLocalRef;
	final decimalKind:WasmLocalRef;
	final significandWork:WasmLocalRef;
	final significandDigitCount:WasmLocalRef;
	final isNegative:WasmLocalRef;
	final decimalPointPosition:WasmLocalRef;
	final useScientificNotation:WasmLocalRef;
	final scientificExponent:WasmLocalRef;
	final exponentMagnitude:WasmLocalRef;
	final exponentDigitCount:WasmLocalRef;
	final outputLength:WasmLocalRef;
	final outputString:WasmLocalRef;
	final digitIndex:WasmLocalRef;
	final digitValue:WasmLocalRef;
	final significandDigitOffset:WasmLocalRef;
	final outputOffset:WasmLocalRef;
	final exponentStart:WasmLocalRef;
	final numericWork:WasmLocalRef;
	final exponentDigitIndex:WasmLocalRef;
}

/** Ryū binary64 conversion and Haxeon string rendering for linear-memory Wasm. */
class WasmNumericString {
	static inline final STRING_DATA_OFFSET = WasmLayout.STRING_DATA_OFFSET;
	static inline final STRING_LENGTH_OFFSET = WasmLayout.STRING_LENGTH_OFFSET;
	static inline final ARRAY_CAPACITY_OFFSET = WasmLayout.ARRAY_CAPACITY_OFFSET;

	public static function addFloatToString(module:WasmModule, name:String, allocator:Int, bytesTypeId:Int, tableBase:Int, nanString:Int, infinityString:Int,
			negativeInfinityString:Int, zeroString:Int):Int {
		var umul = addUnsignedMultiply128(module, '__${name}_umul128'),
			mulShift = addMultiplyShift(module, '__${name}_mul_shift', umul),
			mulShiftAll = addMultiplyShiftAll(module, '__${name}_mul_shift_all', mulShift),
			pow5Factor = addPow5Factor(module, '__${name}_pow5_factor');
		var decimal = addDoubleToDecimal(module, '__${name}_decimal', mulShiftAll, pow5Factor),
			builder = new WasmFunctionBuilder(name, {parameters: [F64], results: [I32]}),
			value = builder.parameter("value", 0),
			decimalExponent = builder.local("decimalExponent", I32),
			significand = builder.local("significand", I64),
			decimalKind = builder.local("decimalKind", I32),
			significandWork = builder.local("significandWork", I64),
			significandDigitCount = builder.local("significandDigitCount", I32),
			isNegative = builder.local("isNegative", I32),
			decimalPointPosition = builder.local("decimalPointPosition", I32),
			useScientificNotation = builder.local("useScientificNotation", I32),
			scientificExponent = builder.local("scientificExponent", I32),
			exponentMagnitude = builder.local("exponentMagnitude", I32),
			exponentDigitCount = builder.local("exponentDigitCount", I32),
			outputLength = builder.local("outputLength", I32),
			outputString = builder.local("outputString", I32),
			digitIndex = builder.local("digitIndex", I32),
			digitValue = builder.local("digitValue", I32),
			significandDigitOffset = builder.local("significandDigitOffset", I32),
			outputOffset = builder.local("outputOffset", I32),
			exponentStart = builder.local("exponentStart", I32),
			numericWork = builder.local("numericWork", I32),
			exponentDigitIndex = builder.local("exponentDigitIndex", I32);
		var locals:FloatStringLocals = {
			value: value,
			decimalExponent: decimalExponent,
			significand: significand,
			decimalKind: decimalKind,
			significandWork: significandWork,
			significandDigitCount: significandDigitCount,
			isNegative: isNegative,
			decimalPointPosition: decimalPointPosition,
			useScientificNotation: useScientificNotation,
			scientificExponent: scientificExponent,
			exponentMagnitude: exponentMagnitude,
			exponentDigitCount: exponentDigitCount,
			outputLength: outputLength,
			outputString: outputString,
			digitIndex: digitIndex,
			digitValue: digitValue,
			significandDigitOffset: significandDigitOffset,
			outputOffset: outputOffset,
			exponentStart: exponentStart,
			numericWork: numericWork,
			exponentDigitIndex: exponentDigitIndex
		};

		builder.emitAll([
			LocalGet(locals.value),
			I32Const(tableBase),
			I32Const(tableBase + WasmRyuTables.INVERSE_ENTRIES * 16),
			Call(decimal),
			LocalSet(locals.decimalKind),
			LocalSet(locals.decimalExponent),
			LocalSet(locals.significand)
		]);
		appendSpecialValueReturns(builder, locals, nanString, infinityString, negativeInfinityString, zeroString);
		appendSignificandShape(builder, locals);
		appendOutputLayout(builder, locals);
		appendOutputStringAllocation(builder, locals, allocator, bytesTypeId);
		appendSignificandDigits(builder, locals);
		builder.localGet(locals.useScientificNotation);
		builder.ifElse(
			function(builder) appendScientificBranch(builder, locals),
			function(builder) appendFixedBranch(builder, locals)
		);
		builder.localGet(locals.outputString);
		builder.return_();
		return module.addFunction(builder.finish());
	}

	static function appendSpecialValueReturns(
			builder:WasmFunctionBuilder, locals:FloatStringLocals, nanString:Int, infinityString:Int, negativeInfinityString:Int, zeroString:Int):Void {
		builder.emitAll([
			LocalGet(locals.decimalKind),
			I32Const(2),
			I32Eq,
			If(null),
			I32Const(nanString),
			Return,
			End,
			LocalGet(locals.decimalKind),
			I32Const(3),
			I32Eq,
			If(null),
			I32Const(infinityString),
			Return,
			End,
			LocalGet(locals.decimalKind),
			I32Const(4),
			I32Eq,
			If(null),
			I32Const(negativeInfinityString),
			Return,
			End,
			LocalGet(locals.decimalKind),
			I32Const(5),
			I32Eq,
			If(null),
			I32Const(zeroString),
			Return,
			End,
		]);
	}

	static function appendSignificandShape(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			LocalGet(locals.decimalKind),
			I32Const(1),
			I32Eq,
			If(I32),
			I32Const(1),
			Else,
			I32Const(0),
			End,
			LocalSet(locals.isNegative),
			LocalGet(locals.significand),
			LocalSet(locals.significandWork),
			I32Const(1),
			LocalSet(locals.significandDigitCount),
			Block(null),
			Loop(null),
			LocalGet(locals.significandWork),
			I64Const(10),
			I64LtS,
			BrIf(1),
			LocalGet(locals.significandWork),
			I64Const(10),
			I64DivS,
			LocalSet(locals.significandWork),
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32Add,
			LocalSet(locals.significandDigitCount),
			Br(0),
			End,
			End,
			LocalGet(locals.significandDigitCount),
			LocalGet(locals.decimalExponent),
			I32Add,
			LocalSet(locals.decimalPointPosition),
		]);
	}

	static function appendOutputLayout(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			// Haxe-style general number rendering: fixed in (-6, 21], scientific otherwise.
			I32Const(0),
			LocalSet(locals.useScientificNotation),
			LocalGet(locals.decimalPointPosition),
			I32Const(21),
			I32LeS,
			I32Eqz,
			If(null),
			I32Const(1),
			LocalSet(locals.useScientificNotation),
			End,
			LocalGet(locals.decimalPointPosition),
			I32Const(-6),
			I32LeS,
			If(null),
			I32Const(1),
			LocalSet(locals.useScientificNotation),
			End,
			LocalGet(locals.useScientificNotation),
			If(null),
			LocalGet(locals.decimalPointPosition),
			I32Const(1),
			I32Sub,
			LocalSet(locals.scientificExponent),
			LocalGet(locals.scientificExponent),
			I32Const(0),
			I32LtS,
			If(I32),
			I32Const(0),
			LocalGet(locals.scientificExponent),
			I32Sub,
			Else,
			LocalGet(locals.scientificExponent),
			End,
			LocalSet(locals.exponentMagnitude),
			LocalGet(locals.exponentMagnitude),
			LocalSet(locals.numericWork),
			I32Const(1),
			LocalSet(locals.exponentDigitCount),
			Block(null),
			Loop(null),
			LocalGet(locals.numericWork),
			I32Const(10),
			I32LtS,
			BrIf(1),
			LocalGet(locals.numericWork),
			I32Const(10),
			I32DivS,
			LocalSet(locals.numericWork),
			LocalGet(locals.exponentDigitCount),
			I32Const(1),
			I32Add,
			LocalSet(locals.exponentDigitCount),
			Br(0),
			End,
			End,
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitCount),
			I32Add,
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32LeS,
			If(I32),
			I32Const(0),
			Else,
			I32Const(1),
			End,
			I32Add,
			I32Const(2),
			I32Add,
			LocalGet(locals.exponentDigitCount),
			I32Add,
			LocalSet(locals.outputLength),
			Else,
			LocalGet(locals.decimalPointPosition),
			I32Const(0),
			I32LeS,
			If(null),
			LocalGet(locals.isNegative),
			I32Const(2),
			I32Add,
			LocalGet(locals.decimalPointPosition),
			I32Sub,
			LocalGet(locals.significandDigitCount),
			I32Add,
			LocalSet(locals.outputLength),
			Else,
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitCount),
			I32LtS,
			If(null),
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitCount),
			I32Add,
			I32Const(1),
			I32Add,
			LocalSet(locals.outputLength),
			Else,
			LocalGet(locals.isNegative),
			LocalGet(locals.decimalPointPosition),
			I32Add,
			LocalSet(locals.outputLength),
			End,
			End,
			End,
		]);
	}

	static function appendOutputStringAllocation(builder:WasmFunctionBuilder, locals:FloatStringLocals, allocator:Int, bytesTypeId:Int):Void {
		builder.emitAll([
			LocalGet(locals.outputLength),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			Call(allocator),
			LocalSet(locals.outputString),
			LocalGet(locals.outputString),
			I32Const(bytesTypeId),
			I32Store(0),
			LocalGet(locals.outputString),
			LocalGet(locals.outputLength),
			I32Store(STRING_LENGTH_OFFSET),
			LocalGet(locals.outputString),
			LocalGet(locals.outputLength),
			I32Store(ARRAY_CAPACITY_OFFSET),
			LocalGet(locals.decimalKind),
			I32Const(1),
			I32Eq,
			If(null),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			I32Const(45),
			I32Store8(0),
			End,
		]);
	}

	static function appendSignificandDigits(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			// Store coefficient digits directly at their final output positions, right-to-left.
			LocalGet(locals.significand),
			LocalSet(locals.significandWork),
			I32Const(0),
			LocalSet(locals.digitIndex),
			Block(null),
			Loop(null),
			LocalGet(locals.significandDigitCount),
			LocalGet(locals.digitIndex),
			I32LeS,
			BrIf(1),
			LocalGet(locals.significandWork),
			I64Const(10),
			I64RemS,
			I32WrapI64,
			LocalSet(locals.digitValue),
			LocalGet(locals.significandWork),
			I64Const(10),
			I64DivS,
			LocalSet(locals.significandWork),
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32Sub,
			LocalGet(locals.digitIndex),
			I32Sub,
			LocalSet(locals.significandDigitOffset),
			LocalGet(locals.useScientificNotation),
			If(I32),
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitOffset),
			I32Eqz,
			If(I32),
			I32Const(0),
			Else,
			LocalGet(locals.significandDigitOffset),
			I32Const(1),
			I32Add,
			End,
			I32Add,
			Else,
			LocalGet(locals.decimalPointPosition),
			I32Const(0),
			I32LeS,
			If(I32),
			LocalGet(locals.isNegative),
			I32Const(2),
			I32Add,
			LocalGet(locals.decimalPointPosition),
			I32Sub,
			LocalGet(locals.significandDigitOffset),
			I32Add,
			Else,
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitCount),
			I32LeS,
			If(I32),
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitOffset),
			I32Add,
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitOffset),
			I32LeS,
			If(I32),
			I32Const(1),
			Else,
			I32Const(0),
			End,
			I32Add,
			Else,
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitOffset),
			I32Add,
			End,
			End,
			End,
			LocalSet(locals.outputOffset),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.outputOffset),
			I32Add,
			LocalGet(locals.digitValue),
			I32Const(48),
			I32Add,
			I32Store8(0),
			LocalGet(locals.digitIndex),
			I32Const(1),
			I32Add,
			LocalSet(locals.digitIndex),
			Br(0),
			End,
			End,
		]);
	}

	static function appendScientificBranch(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32LeS,
			I32Eqz,
			If(null),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			I32Add,
			I32Const(1),
			I32Add,
			I32Const(46),
			I32Store8(0),
			End,
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitCount),
			I32Add,
			LocalGet(locals.significandDigitCount),
			I32Const(1),
			I32LeS,
			If(I32),
			I32Const(0),
			Else,
			I32Const(1),
			End,
			I32Add,
			LocalSet(locals.exponentStart),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.exponentStart),
			I32Add,
			I32Const(101),
			I32Store8(0),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.exponentStart),
			I32Const(1),
			I32Add,
			I32Add,
			LocalGet(locals.scientificExponent),
			I32Const(0),
			I32LtS,
			If(I32),
			I32Const(45),
			Else,
			I32Const(43),
			End,
			I32Store8(0),
			LocalGet(locals.exponentStart),
			I32Const(2),
			I32Add,
			LocalSet(locals.exponentStart),
			LocalGet(locals.exponentDigitCount),
			LocalSet(locals.exponentDigitIndex),
			I32Const(0),
			LocalSet(locals.digitIndex),
			LocalGet(locals.exponentMagnitude),
			LocalSet(locals.numericWork),
			Block(null),
			Loop(null),
			LocalGet(locals.exponentDigitIndex),
			LocalGet(locals.digitIndex),
			I32LeS,
			BrIf(1),
			LocalGet(locals.numericWork),
			I32Const(10),
			I32RemS,
			I32Const(48),
			I32Add,
			LocalSet(locals.digitValue),
			LocalGet(locals.numericWork),
			I32Const(10),
			I32DivS,
			LocalSet(locals.numericWork),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.exponentStart),
			LocalGet(locals.exponentDigitIndex),
			I32Add,
			LocalGet(locals.digitIndex),
			I32Sub,
			I32Const(1),
			I32Sub,
			I32Add,
			LocalGet(locals.digitValue),
			I32Store8(0),
			LocalGet(locals.digitIndex),
			I32Const(1),
			I32Add,
			LocalSet(locals.digitIndex),
			Br(0),
			End,
			End,
		]);
	}

	static function appendFixedBranch(builder:WasmFunctionBuilder, locals:FloatStringLocals):Void {
		builder.emitAll([
			LocalGet(locals.decimalPointPosition),
			I32Const(0),
			I32LeS,
			If(null),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			I32Add,
			I32Const(48),
			I32Store8(0),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			I32Const(1),
			I32Add,
			I32Add,
			I32Const(46),
			I32Store8(0),
			I32Const(0),
			LocalSet(locals.digitIndex),
			I32Const(0),
			LocalGet(locals.decimalPointPosition),
			I32Sub,
			LocalSet(locals.outputOffset),
			Block(null),
			Loop(null),
			LocalGet(locals.outputOffset),
			LocalGet(locals.digitIndex),
			I32LeS,
			BrIf(1),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			I32Const(2),
			I32Add,
			LocalGet(locals.digitIndex),
			I32Add,
			I32Add,
			I32Const(48),
			I32Store8(0),
			LocalGet(locals.digitIndex),
			I32Const(1),
			I32Add,
			LocalSet(locals.digitIndex),
			Br(0),
			End,
			End,
			Else,
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitCount),
			I32LtS,
			If(null),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			LocalGet(locals.decimalPointPosition),
			I32Add,
			I32Add,
			I32Const(46),
			I32Store8(0),
			Else,
			I32Const(0),
			LocalSet(locals.digitIndex),
			LocalGet(locals.decimalPointPosition),
			LocalGet(locals.significandDigitCount),
			I32Sub,
			LocalSet(locals.outputOffset),
			Block(null),
			Loop(null),
			LocalGet(locals.outputOffset),
			LocalGet(locals.digitIndex),
			I32LeS,
			BrIf(1),
			LocalGet(locals.outputString),
			I32Const(STRING_DATA_OFFSET),
			I32Add,
			LocalGet(locals.isNegative),
			LocalGet(locals.significandDigitCount),
			I32Add,
			LocalGet(locals.digitIndex),
			I32Add,
			I32Add,
			I32Const(48),
			I32Store8(0),
			LocalGet(locals.digitIndex),
			I32Const(1),
			I32Add,
			LocalSet(locals.digitIndex),
			Br(0),
			End,
			End,
			End,
			End,
		]);
	}

	static function addUnsignedMultiply128(module:WasmModule, name:String):Int {
		var builder = new WasmFunctionBuilder(name, {parameters: [I64, I64], results: [I64, I64]}),
			left = builder.parameter("left", 0),
			right = builder.parameter("right", 1),
			leftLow = builder.local("leftLow", I64),
			leftHigh = builder.local("leftHigh", I64),
			rightLow = builder.local("rightLow", I64),
			rightHigh = builder.local("rightHigh", I64),
			lowProduct = builder.local("lowProduct", I64),
			leftLowRightHighProduct = builder.local("leftLowRightHighProduct", I64),
			leftHighRightLowProduct = builder.local("leftHighRightLowProduct", I64),
			highProduct = builder.local("highProduct", I64),
			lowWord = builder.local("lowWord", I64),
			lowProductCarry = builder.local("lowProductCarry", I64),
			crossTerm = builder.local("crossTerm", I64),
			crossTermLowWord = builder.local("crossTermLowWord", I64),
			crossTermCarry = builder.local("crossTermCarry", I64),
			middleTerm = builder.local("middleTerm", I64),
			middleTermLowWord = builder.local("middleTermLowWord", I64),
			middleTermCarry = builder.local("middleTermCarry", I64),
			productLow = builder.local("productLow", I64),
			productHigh = builder.local("productHigh", I64);
		builder.emitAll([
			LocalGet(left),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(leftLow),
			LocalGet(left),
			I64Const(32),
			I64ShrU,
			LocalSet(leftHigh),
			LocalGet(right),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(rightLow),
			LocalGet(right),
			I64Const(32),
			I64ShrU,
			LocalSet(rightHigh),
			LocalGet(leftLow),
			LocalGet(rightLow),
			I64Mul,
			LocalSet(lowProduct),
			LocalGet(leftLow),
			LocalGet(rightHigh),
			I64Mul,
			LocalSet(leftLowRightHighProduct),
			LocalGet(leftHigh),
			LocalGet(rightLow),
			I64Mul,
			LocalSet(leftHighRightLowProduct),
			LocalGet(leftHigh),
			LocalGet(rightHigh),
			I64Mul,
			LocalSet(highProduct),
			LocalGet(lowProduct),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(lowWord),
			LocalGet(lowProduct),
			I64Const(32),
			I64ShrU,
			LocalSet(lowProductCarry),
			LocalGet(leftHighRightLowProduct),
			LocalGet(lowProductCarry),
			I64Add,
			LocalSet(crossTerm),
			LocalGet(crossTerm),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(crossTermLowWord),
			LocalGet(crossTerm),
			I64Const(32),
			I64ShrU,
			LocalSet(crossTermCarry),
			LocalGet(leftLowRightHighProduct),
			LocalGet(crossTermLowWord),
			I64Add,
			LocalSet(middleTerm),
			LocalGet(middleTerm),
			I32WrapI64,
			I64ExtendI32U,
			LocalSet(middleTermLowWord),
			LocalGet(middleTerm),
			I64Const(32),
			I64ShrU,
			LocalSet(middleTermCarry),
			LocalGet(middleTermLowWord),
			I64Const(32),
			I64Shl,
			LocalGet(lowWord),
			I64Or,
			LocalSet(productLow),
			LocalGet(highProduct),
			LocalGet(crossTermCarry),
			I64Add,
			LocalGet(middleTermCarry),
			I64Add,
			LocalSet(productHigh),
			LocalGet(productLow),
			LocalGet(productHigh),
			Return
		]);
		return module.addFunction(builder.finish());
	}

	static function addMultiplyShift(module:WasmModule, name:String, umul:Int):Int {
		var builder = new WasmFunctionBuilder(name, {parameters: [I64, I32, I32], results: [I64]}),
			value = builder.parameter("value", 0),
			tableBase = builder.parameter("tableBase", 1),
			bitShift = builder.parameter("bitShift", 2),
			lowProduct = builder.local("lowProduct", I64),
			highProduct = builder.local("highProduct", I64),
			lowerCrossProduct = builder.local("lowerCrossProduct", I64),
			shiftedLowWord = builder.local("shiftedLowWord", I64),
			carry = builder.local("carry", I32),
			complementaryShift = builder.local("complementaryShift", I32);
		builder.emitAll([
			LocalGet(value),
			LocalGet(tableBase),
			I64Load(8),
			Call(umul),
			LocalSet(highProduct),
			LocalSet(lowProduct),
			LocalGet(value),
			LocalGet(tableBase),
			I64Load(0),
			Call(umul),
			LocalSet(lowerCrossProduct),
			Drop,
			LocalGet(lowerCrossProduct),
			LocalGet(lowProduct),
			I64Add,
			LocalSet(shiftedLowWord),
			LocalGet(shiftedLowWord),
			LocalGet(lowerCrossProduct),
			I64LtU,
			LocalSet(carry),
			LocalGet(highProduct),
			LocalGet(carry),
			I64ExtendI32U,
			I64Add,
			LocalSet(highProduct),
			LocalGet(bitShift),
			I32Const(64),
			I32Sub,
			LocalSet(complementaryShift),
			LocalGet(highProduct),
			I32Const(64),
			LocalGet(complementaryShift),
			I32Sub,
			I64ExtendI32U,
			I64Shl,
			LocalGet(shiftedLowWord),
			LocalGet(complementaryShift),
			I64ExtendI32U,
			I64ShrU,
			I64Or,
			Return
		]);
		return module.addFunction(builder.finish());
	}

	static function addMultiplyShiftAll(module:WasmModule, name:String, mulShift:Int):Int {
		var builder = new WasmFunctionBuilder(name, {parameters: [I64, I32, I32, I32], results: [I64, I64, I64]}),
			significand = builder.parameter("significand", 0),
			tableBase = builder.parameter("tableBase", 1),
			bitShift = builder.parameter("bitShift", 2),
			mmShift = builder.parameter("mmShift", 3);
		builder.emitAll([
			LocalGet(significand),
			I64Const(2),
			I64Shl,
			LocalGet(tableBase),
			LocalGet(bitShift),
			Call(mulShift),
			LocalGet(significand),
			I64Const(2),
			I64Shl,
			I64Const(2),
			I64Add,
			LocalGet(tableBase),
			LocalGet(bitShift),
			Call(mulShift),
			LocalGet(significand),
			I64Const(2),
			I64Shl,
			I64Const(1),
			I64Sub,
			LocalGet(mmShift),
			I64ExtendI32U,
			I64Sub,
			LocalGet(tableBase),
			LocalGet(bitShift),
			Call(mulShift),
			Return
		]);
		return module.addFunction(builder.finish());
	}

	static function addPow5Factor(module:WasmModule, name:String):Int {
		var builder = new WasmFunctionBuilder(name, {parameters: [I64], results: [I32]}),
			value = builder.parameter("value", 0),
			factorCount = builder.local("factorCount", I32);
		builder.emitAll([
			I32Const(0),
			LocalSet(factorCount),
			Block(null),
			Loop(null),
			LocalGet(value),
			I64Const(5),
			I64RemS,
			I64Eqz,
			I32Eqz,
			BrIf(1),
			LocalGet(value),
			I64Const(5),
			I64DivS,
			LocalSet(value),
			LocalGet(factorCount),
			I32Const(1),
			I32Add,
			LocalSet(factorCount),
			Br(0),
			End,
			End,
			LocalGet(factorCount),
			Return
		]);
		return module.addFunction(builder.finish());
	}

	static function addDoubleToDecimal(module:WasmModule, name:String, mulShiftAll:Int, pow5Factor:Int):Int {
		var builder = new WasmFunctionBuilder(name, {parameters: [F64, I32, I32], results: [I64, I32, I32]}),
			value = builder.parameter("value", 0),
			inverseTable = builder.parameter("inverseTable", 1),
			powerTable = builder.parameter("powerTable", 2),
			bits = builder.local("bits", I64),
			sign = builder.local("sign", I32),
			fraction = builder.local("fraction", I64),
			exponentField = builder.local("exponentField", I32),
			significand = builder.local("significand", I64),
			binaryExponent = builder.local("binaryExponent", I32),
			acceptBounds = builder.local("acceptBounds", I32),
			mmShift = builder.local("mmShift", I32),
			fourTimesSignificand = builder.local("fourTimesSignificand", I64),
			q = builder.local("q", I32),
			decimalExponent = builder.local("decimalExponent", I32),
			powerOfFiveIndex = builder.local("powerOfFiveIndex", I32),
			log2PowerOfFive = builder.local("log2PowerOfFive", I32),
			binaryShift = builder.local("binaryShift", I32),
			tablePointer = builder.local("tablePointer", I32),
			center = builder.local("center", I64),
			upperBound = builder.local("upperBound", I64),
			lowerBound = builder.local("lowerBound", I64),
			lowerBoundIsTrailingZeros = builder.local("lowerBoundIsTrailingZeros", I32),
			centerIsTrailingZeros = builder.local("centerIsTrailingZeros", I32),
			negativeBinaryExponent = builder.local("negativeBinaryExponent", I32),
			removedDigitCount = builder.local("removedDigitCount", I32),
			lastRemovedDigit = builder.local("lastRemovedDigit", I32),
			centerQuotient = builder.local("centerQuotient", I64),
			upperBoundQuotient = builder.local("upperBoundQuotient", I64),
			lowerBoundQuotient = builder.local("lowerBoundQuotient", I64),
			remainder = builder.local("remainder", I32),
			powerOfFiveFactor = builder.local("powerOfFiveFactor", I32),
			roundUpForDiscardedDigits = builder.local("roundUpForDiscardedDigits", I32);
		// Both exponent branches scale the same center and rounding interval.
		function appendScaledInterval():Void {
			builder.emitAll([
				LocalGet(significand),
				LocalGet(tablePointer),
				LocalGet(binaryShift),
				LocalGet(mmShift),
				Call(mulShiftAll),
				LocalSet(lowerBound),
				LocalSet(upperBound),
				LocalSet(center)
			]);
		}
		builder.emitAll([
			LocalGet(value),
			I64ReinterpretF64,
			LocalSet(bits),
			LocalGet(bits),
			I64Const(63),
			I64ShrU,
			I32WrapI64,
			LocalSet(sign),
			I64Const(-1),
			I64Const(12),
			I64ShrU,
			LocalGet(bits),
			I64And,
			LocalSet(fraction),
			LocalGet(bits),
			I64Const(52),
			I64ShrU,
			I64Const(2047),
			I64And,
			I32WrapI64,
			LocalSet(exponentField),
			// NaN has a non-zero payload; infinities have a zero payload.
			LocalGet(exponentField),
			I32Const(2047),
			I32Eq,
			If(null),
			LocalGet(fraction),
			I64Eqz,
			I32Eqz,
			If(null),
			I64Const(0),
			I32Const(0),
			I32Const(2),
			Return,
			End,
			I64Const(0),
			I32Const(0),
			LocalGet(sign),
			If(I32),
			I32Const(4),
			Else,
			I32Const(3),
			End,
			Return,
			End,
			LocalGet(exponentField),
			I32Eqz,
			LocalGet(fraction),
			I64Eqz,
			I32And,
			If(null),
			I64Const(0),
			I32Const(0),
			I32Const(5),
			Return,
			End,
			// Decode the finite IEEE-754 value into m2 * 2^e2.
			LocalGet(exponentField),
			I32Eqz,
			If(null),
			I32Const(-1076),
			LocalSet(binaryExponent),
			LocalGet(fraction),
			LocalSet(significand),
			Else,
			LocalGet(exponentField),
			I32Const(1077),
			I32Sub,
			LocalSet(binaryExponent),
			LocalGet(fraction),
			I64Const(1),
			I64Const(52),
			I64Shl,
			I64Add,
			LocalSet(significand),
			End,
			LocalGet(significand),
			I64Const(1),
			I64And,
			I64Eqz,
			LocalSet(acceptBounds),
			LocalGet(fraction),
			I64Eqz,
			I32Eqz,
			LocalGet(exponentField),
			I32Const(1),
			I32LeS,
			I32Or,
			LocalSet(mmShift),
			LocalGet(significand),
			I64Const(2),
			I64Shl,
			LocalSet(fourTimesSignificand),
			I32Const(0),
			LocalSet(lowerBoundIsTrailingZeros),
			I32Const(0),
			LocalSet(centerIsTrailingZeros),
			LocalGet(binaryExponent),
			I32Const(0),
			I32LtS,
			If(null),
			// e2 < 0: multiply by a split power of five.
			I32Const(0),
			LocalGet(binaryExponent),
			I32Sub,
			LocalSet(negativeBinaryExponent),
			LocalGet(negativeBinaryExponent),
			I32Const(732923),
			I32Mul,
			I32Const(20),
			I32ShrU,
			LocalSet(q),
			LocalGet(negativeBinaryExponent),
			I32Const(1),
			I32LeS,
			If(null),
			Else,
			LocalGet(q),
			I32Const(1),
			I32Sub,
			LocalSet(q),
			End,
			LocalGet(q),
			LocalGet(binaryExponent),
			I32Add,
			LocalSet(decimalExponent),
			LocalGet(negativeBinaryExponent),
			LocalGet(q),
			I32Sub,
			LocalSet(powerOfFiveIndex),
			LocalGet(powerOfFiveIndex),
			I32Const(1217359),
			I32Mul,
			I32Const(19),
			I32ShrU,
			I32Const(1),
			I32Add,
			I32Const(125),
			I32Sub,
			LocalSet(log2PowerOfFive),
			LocalGet(q),
			LocalGet(log2PowerOfFive),
			I32Sub,
			LocalSet(binaryShift),
			LocalGet(powerTable),
			LocalGet(powerOfFiveIndex),
			I32Const(4),
			I32Shl,
			I32Add,
			LocalSet(tablePointer),
		]);
		appendScaledInterval();
		builder.emitAll([
			LocalGet(q),
			I32Const(1),
			I32LeS,
			If(null),
			I32Const(1),
			LocalSet(centerIsTrailingZeros),
			LocalGet(acceptBounds),
			If(null),
			LocalGet(mmShift),
			I32Const(1),
			I32Eq,
			LocalSet(lowerBoundIsTrailingZeros),
			Else,
			LocalGet(upperBound),
			I64Const(1),
			I64Sub,
			LocalSet(upperBound),
			End,
			Else,
			I32Const(63),
			LocalGet(q),
			I32LtS,
			If(null),
			I64Const(1),
			LocalGet(q),
			I64ExtendI32U,
			I64Shl,
			I64Const(1),
			I64Sub,
			LocalGet(fourTimesSignificand),
			I64And,
			I64Eqz,
			LocalSet(centerIsTrailingZeros),
			End,
			End,
			Else,
			// e2 >= 0: divide by a split inverse power of five.
			LocalGet(binaryExponent),
			I32Const(78913),
			I32Mul,
			I32Const(18),
			I32ShrU,
			LocalSet(q),
			LocalGet(binaryExponent),
			I32Const(3),
			I32LeS,
			If(null),
			Else,
			LocalGet(q),
			I32Const(1),
			I32Sub,
			LocalSet(q),
			End,
			LocalGet(q),
			LocalSet(decimalExponent),
			LocalGet(q),
			I32Const(1217359),
			I32Mul,
			I32Const(19),
			I32ShrU,
			I32Const(125),
			I32Add,
			LocalSet(log2PowerOfFive),
			I32Const(0),
			LocalGet(binaryExponent),
			I32Sub,
			LocalGet(q),
			I32Add,
			LocalGet(log2PowerOfFive),
			I32Add,
			LocalSet(binaryShift),
			LocalGet(inverseTable),
			LocalGet(q),
			I32Const(4),
			I32Shl,
			I32Add,
			LocalSet(tablePointer),
		]);
		appendScaledInterval();
		builder.emitAll([
			LocalGet(q),
			I32Const(21),
			I32LeS,
			If(null),
			LocalGet(fourTimesSignificand),
			I64Const(5),
			I64RemS,
			I64Eqz,
			If(null),
			LocalGet(fourTimesSignificand),
			Call(pow5Factor),
			LocalSet(powerOfFiveFactor),
			LocalGet(q),
			LocalGet(powerOfFiveFactor),
			I32LeS,
			LocalSet(centerIsTrailingZeros),
			Else,
			LocalGet(acceptBounds),
			If(null),
			LocalGet(fourTimesSignificand),
			I64Const(1),
			I64Sub,
			LocalGet(mmShift),
			I64ExtendI32U,
			I64Sub,
			Call(pow5Factor),
			LocalSet(powerOfFiveFactor),
			LocalGet(q),
			LocalGet(powerOfFiveFactor),
			I32LeS,
			LocalSet(lowerBoundIsTrailingZeros),
			Else,
			LocalGet(fourTimesSignificand),
			I64Const(2),
			I64Add,
			Call(pow5Factor),
			LocalSet(powerOfFiveFactor),
			LocalGet(upperBound),
			LocalGet(q),
			LocalGet(powerOfFiveFactor),
			I32LeS,
			If(I32),
			I32Const(1),
			Else,
			I32Const(0),
			End,
			I64ExtendI32U,
			I64Sub,
			LocalSet(upperBound),
			End,
			End,
			End,
			End,
			// Remove digits while the rounded interval still contains a representation.
			I32Const(0),
			LocalSet(removedDigitCount),
			I32Const(0),
			LocalSet(lastRemovedDigit),
			LocalGet(lowerBoundIsTrailingZeros),
			LocalGet(centerIsTrailingZeros),
			I32Or,
			If(null),
			Block(null),
			Loop(null),
			LocalGet(upperBound),
			I64Const(10),
			I64DivS,
			LocalSet(upperBoundQuotient),
			LocalGet(lowerBound),
			I64Const(10),
			I64DivS,
			LocalSet(lowerBoundQuotient),
			LocalGet(upperBoundQuotient),
			LocalGet(lowerBoundQuotient),
			I64LeS,
			BrIf(1),
			LocalGet(lowerBound),
			LocalGet(lowerBoundQuotient),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(remainder),
			LocalGet(center),
			I64Const(10),
			I64DivS,
			LocalSet(centerQuotient),
			LocalGet(center),
			LocalGet(centerQuotient),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(lastRemovedDigit),
			LocalGet(lowerBoundIsTrailingZeros),
			LocalGet(remainder),
			I32Eqz,
			I32And,
			LocalSet(lowerBoundIsTrailingZeros),
			LocalGet(centerIsTrailingZeros),
			LocalGet(lastRemovedDigit),
			I32Eqz,
			I32And,
			LocalSet(centerIsTrailingZeros),
			LocalGet(centerQuotient),
			LocalSet(center),
			LocalGet(upperBoundQuotient),
			LocalSet(upperBound),
			LocalGet(lowerBoundQuotient),
			LocalSet(lowerBound),
			LocalGet(removedDigitCount),
			I32Const(1),
			I32Add,
			LocalSet(removedDigitCount),
			Br(0),
			End,
			End,
			LocalGet(lowerBoundIsTrailingZeros),
			If(null),
			Block(null),
			Loop(null),
			LocalGet(lowerBound),
			I64Const(10),
			I64DivS,
			LocalSet(lowerBoundQuotient),
			LocalGet(lowerBound),
			LocalGet(lowerBoundQuotient),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			I32Eqz,
			I32Eqz,
			BrIf(1),
			LocalGet(center),
			I64Const(10),
			I64DivS,
			LocalSet(upperBoundQuotient),
			LocalGet(center),
			LocalGet(upperBoundQuotient),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(lastRemovedDigit),
			LocalGet(centerIsTrailingZeros),
			LocalGet(lastRemovedDigit),
			I32Eqz,
			I32And,
			LocalSet(centerIsTrailingZeros),
			LocalGet(upperBound),
			I64Const(10),
			I64DivS,
			LocalSet(upperBound),
			LocalGet(upperBoundQuotient),
			LocalSet(center),
			LocalGet(lowerBoundQuotient),
			LocalSet(lowerBound),
			LocalGet(removedDigitCount),
			I32Const(1),
			I32Add,
			LocalSet(removedDigitCount),
			Br(0),
			End,
			End,
			End,
			LocalGet(centerIsTrailingZeros),
			If(null),
			LocalGet(lastRemovedDigit),
			I32Const(5),
			I32Eq,
			LocalGet(center),
			I64Const(1),
			I64And,
			I64Eqz,
			I32And,
			If(null),
			I32Const(4),
			LocalSet(lastRemovedDigit),
			End,
			End,
			LocalGet(center),
			LocalGet(center),
			LocalGet(lowerBound),
			I64Eq,
			LocalGet(acceptBounds),
			I32Eqz,
			LocalGet(lowerBoundIsTrailingZeros),
			I32Eqz,
			I32Or,
			I32And,
			I32Const(5),
			LocalGet(lastRemovedDigit),
			I32LeS,
			I32Or,
			I64ExtendI32U,
			I64Add,
			LocalSet(centerQuotient),
			Else,
			I32Const(0),
			LocalSet(roundUpForDiscardedDigits),
			LocalGet(upperBound),
			I64Const(100),
			I64DivS,
			LocalSet(upperBoundQuotient),
			LocalGet(lowerBound),
			I64Const(100),
			I64DivS,
			LocalSet(lowerBoundQuotient),
			LocalGet(lowerBoundQuotient),
			LocalGet(upperBoundQuotient),
			I64LtS,
			If(null),
			LocalGet(center),
			I64Const(100),
			I64DivS,
			LocalSet(centerQuotient),
			LocalGet(center),
			LocalGet(centerQuotient),
			I64Const(100),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(remainder),
			I32Const(50),
			LocalGet(remainder),
			I32LeS,
			LocalSet(roundUpForDiscardedDigits),
			LocalGet(centerQuotient),
			LocalSet(center),
			LocalGet(upperBoundQuotient),
			LocalSet(upperBound),
			LocalGet(lowerBoundQuotient),
			LocalSet(lowerBound),
			LocalGet(removedDigitCount),
			I32Const(2),
			I32Add,
			LocalSet(removedDigitCount),
			End,
			Block(null),
			Loop(null),
			LocalGet(upperBound),
			I64Const(10),
			I64DivS,
			LocalSet(upperBoundQuotient),
			LocalGet(lowerBound),
			I64Const(10),
			I64DivS,
			LocalSet(lowerBoundQuotient),
			LocalGet(upperBoundQuotient),
			LocalGet(lowerBoundQuotient),
			I64LeS,
			BrIf(1),
			LocalGet(center),
			I64Const(10),
			I64DivS,
			LocalSet(centerQuotient),
			LocalGet(center),
			LocalGet(centerQuotient),
			I64Const(10),
			I64Mul,
			I64Sub,
			I32WrapI64,
			LocalSet(remainder),
			I32Const(5),
			LocalGet(remainder),
			I32LeS,
			LocalSet(roundUpForDiscardedDigits),
			LocalGet(centerQuotient),
			LocalSet(center),
			LocalGet(upperBoundQuotient),
			LocalSet(upperBound),
			LocalGet(lowerBoundQuotient),
			LocalSet(lowerBound),
			LocalGet(removedDigitCount),
			I32Const(1),
			I32Add,
			LocalSet(removedDigitCount),
			Br(0),
			End,
			End,
			LocalGet(center),
			LocalGet(center),
			LocalGet(lowerBound),
			I64Eq,
			LocalGet(roundUpForDiscardedDigits),
			I32Or,
			I64ExtendI32U,
			I64Add,
			LocalSet(centerQuotient),
			End,
			LocalGet(centerQuotient),
			LocalGet(decimalExponent),
			LocalGet(removedDigitCount),
			I32Add,
			LocalGet(sign),
			Return
		]);
		return module.addFunction(builder.finish());
	}

	static function append(body:Array<WasmInstruction>, instructions:Array<WasmInstruction>):Void
		for (instruction in instructions)
			body.push(instruction);
}
