#!/usr/bin/env python3
"""Generate the immutable binary64 Ryū powers embedded by the Wasm runtime."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INVERSE_ENTRIES = 342
POWER_ENTRIES = 326
CHUNK_CHARS = 112


def words_for(value: int) -> list[int]:
    return [(value >> shift) & 0xFFFFFFFF for shift in range(0, 128, 32)]


def table_words() -> list[int]:
    words: list[int] = []
    power = 1
    for _ in range(INVERSE_ENTRIES):
        numerator = 1 << (power.bit_length() - 1 + 125)
        words.extend(words_for(numerator // power + 1))
        power *= 5

    power = 1
    for _ in range(POWER_ENTRIES):
        shift = power.bit_length() - 125
        multiplier = power >> shift if shift >= 0 else power << -shift
        words.extend(words_for(multiplier))
        power *= 5
    return words


def source() -> str:
    raw = b"".join(word.to_bytes(4, "little") for word in table_words())
    encoded = raw.hex()
    chunks = [encoded[index : index + CHUNK_CHARS] for index in range(0, len(encoded), CHUNK_CHARS)]
    lines = [
        "package runtime;",
        "",
        "/** Generated by scripts/generate-ryu-table-data.py; do not edit by hand. */",
        "class RyuTableData {",
        "\tpublic static function address():Int {",
        "\t\treturn RuntimeData.address([",
    ]
    lines.extend(f'\t\t\t"{chunk}",' for chunk in chunks)
    lines.extend(["\t\t]);", "\t}", "}", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    (ROOT / "stdlib/runtime/RyuTableData.hx").write_text(source(), encoding="utf-8")
