HL_PRIM int HL_NAME(inspect_patch)( vbyte *bytes, int length ) {
	int base_revision, revision, function_count;
	hl_runtime_status status = hl_runtime_hlp_summary(bytes,length,&base_revision,&revision,&function_count);
	if( status != HL_RUNTIME_OK || base_revision > 0x3FF || revision > 0x3FF || function_count > 0xFFF ) return -1;
	return (base_revision << 22) | (revision << 12) | function_count;
}

DEFINE_PRIM(_ABSTRACT(native_library),native_open,_BYTES _I32);
DEFINE_PRIM(_BOOL,native_close,_ABSTRACT(native_library));
DEFINE_PRIM(_ABSTRACT(native_function),native_resolve,_ABSTRACT(native_library) _BYTES _I32 _BYTES _I32 _I32);
DEFINE_PRIM(_I32,native_call,_ABSTRACT(native_function) _BYTES _I32 _BYTES _I32);
DEFINE_PRIM(_I32,native_last_error,_BYTES _I32);
DEFINE_PRIM(_ABSTRACT(native_callback),native_callback_create,_ABSTRACT(realtime_bytes) _ABSTRACT(realtime_bytes) _ABSTRACT(realtime_bytes) _DYN);
DEFINE_PRIM(_BOOL,native_callback_close,_ABSTRACT(native_callback));
DEFINE_PRIM(_I32,native_callback_error_kind,_ABSTRACT(native_callback));
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_callback_take_error,_ABSTRACT(native_callback));
DEFINE_PRIM(_BYTES,native_utf8_invoke_0,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL);
DEFINE_PRIM(_BYTES,native_utf8_invoke_1,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_2,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_3,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_4,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_5,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_6,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_7,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_8,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_9,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_10,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_11,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_12,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_13,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_14,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_15,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BYTES,native_utf8_invoke_16,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);

DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_0,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_1,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_2,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_3,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_4,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_5,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_6,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_7,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_8,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_9,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_10,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_11,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_12,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_13,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_14,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_15,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_bytes_invoke_16,_BYTES _BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_0,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_1,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_2,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_3,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_4,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_5,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_6,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_7,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_8,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_9,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_10,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_11,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_12,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_13,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_14,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_15,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(native_pointer),native_pointer_invoke_16,_BYTES _BYTES _BYTES _BYTES _BYTES _BOOL _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_BOOL,native_pointer_close,_ABSTRACT(native_pointer));
DEFINE_PRIM(_BOOL,native_pointer_is_closed,_ABSTRACT(native_pointer));
DEFINE_PRIM(_ABSTRACT(native_pointer),structGetPointer,_ABSTRACT(realtime_bytes) _I32 _BOOL);
DEFINE_PRIM(_VOID,structSetPointer,_ABSTRACT(realtime_bytes) _I32 _ABSTRACT(native_pointer) _BOOL);
DEFINE_PRIM(_VOID,structSetBorrowedBytes,_ABSTRACT(realtime_bytes) _I32 _ABSTRACT(realtime_bytes));
DEFINE_PRIM(_BYTES,structGetUtf8,_ABSTRACT(realtime_bytes) _I32 _BOOL);
DEFINE_PRIM(_VOID,structSetUtf8,_ABSTRACT(realtime_bytes) _I32 _BYTES _BOOL);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_0,_BYTES _BYTES _BYTES);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_1,_BYTES _BYTES _BYTES _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_2,_BYTES _BYTES _BYTES _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_3,_BYTES _BYTES _BYTES _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_4,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_5,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_6,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_7,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_8,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_9,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_10,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_11,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_12,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_13,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_14,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_15,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),native_aggregate_invoke_16,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);

DEFINE_PRIM(_DYN,native_invoke_0,_BYTES _BYTES _BYTES);
DEFINE_PRIM(_DYN,native_invoke_1,_BYTES _BYTES _BYTES _DYN);
DEFINE_PRIM(_DYN,native_invoke_2,_BYTES _BYTES _BYTES _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_3,_BYTES _BYTES _BYTES _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_4,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_5,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_6,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_7,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_8,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_9,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_10,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_11,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_12,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_13,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_14,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_15,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);
DEFINE_PRIM(_DYN,native_invoke_16,_BYTES _BYTES _BYTES _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN _DYN);

DEFINE_PRIM(_ABSTRACT(realtime_module),load,_BYTES _I32 _BYTES _I32);
DEFINE_PRIM(_I32,call_i32,_ABSTRACT(realtime_module) _I32);
DEFINE_PRIM(_VOID,call_void,_ABSTRACT(realtime_module) _I32);
DEFINE_PRIM(_BYTES,call_bytes,_ABSTRACT(realtime_module) _I32);
DEFINE_PRIM(_VOID,call_bytes1,_ABSTRACT(realtime_module) _I32 _BYTES);
DEFINE_PRIM(_DYN,call_closure,_ABSTRACT(realtime_module) _I32);
DEFINE_PRIM(_I32,call_closure_i32,_ABSTRACT(realtime_module) _DYN);
DEFINE_PRIM(_DYN,call_object,_ABSTRACT(realtime_module) _I32);
DEFINE_PRIM(_I32,call_i32_object,_ABSTRACT(realtime_module) _I32 _DYN);
DEFINE_PRIM(_I32,validate_call,_ABSTRACT(realtime_module) _I32 _I32);
DEFINE_PRIM(_I32,patch,_ABSTRACT(realtime_module) _BYTES _I32);
DEFINE_PRIM(_I32,allocation_count,_ABSTRACT(realtime_module));
DEFINE_PRIM(_I32,patch_jit_count,_ABSTRACT(realtime_module));
DEFINE_PRIM(_BYTES,jit_location,_ABSTRACT(realtime_module) _I32);
DEFINE_PRIM(_I32,debug_region_count,_ABSTRACT(realtime_module));
DEFINE_PRIM(_I32,retired_allocation_count,_ABSTRACT(realtime_module));
DEFINE_PRIM(_I32,type_count,_ABSTRACT(realtime_module));
DEFINE_PRIM(_I32,type_capacity,_ABSTRACT(realtime_module));
DEFINE_PRIM(_I32,live_allocation_count,_ABSTRACT(realtime_module));
DEFINE_PRIM(_I32,native_root_count,_ABSTRACT(realtime_module));
DEFINE_PRIM(_VOID,retirement_status,_ABSTRACT(realtime_module) _BYTES);
DEFINE_PRIM(_I32,revision,_ABSTRACT(realtime_module));
DEFINE_PRIM(_VOID,set_patch_failure_stage,_ABSTRACT(realtime_module) _I32);
DEFINE_PRIM(_I32,dispose,_ABSTRACT(realtime_module));
DEFINE_PRIM(_I32,retry_failed_retirements,_NO_ARG);
DEFINE_PRIM(_I32,failed_retirement_count,_NO_ARG);
DEFINE_PRIM(_I32,inspect_patch,_BYTES _I32);
DEFINE_PRIM(_VOID,array_int_init,_OBJ(_BYTES _I32));
DEFINE_PRIM(_VOID,array_int_push,_OBJ(_BYTES _I32) _I32);
DEFINE_PRIM(_I32,array_int_get,_OBJ(_BYTES _I32) _I32);
DEFINE_PRIM(_I32,array_int_length,_OBJ(_BYTES _I32));
DEFINE_PRIM(_ARR,array_int_alloc,_I32);
DEFINE_PRIM(_ARR,__array_alloc_i32,_I32);
DEFINE_PRIM(_ARR,__array_alloc_f64,_I32);
DEFINE_PRIM(_ARR,__array_alloc_bytes,_I32);
DEFINE_PRIM(_ARR,__array_alloc_bool,_I32);
DEFINE_PRIM(_ARR,__array_alloc_ref,_I32);
DEFINE_PRIM(_ARR,__array_copy_i32,_ARR);
DEFINE_PRIM(_ARR,__array_copy_f64,_ARR);
DEFINE_PRIM(_ARR,__array_copy_bytes,_ARR);
DEFINE_PRIM(_ARR,__array_copy_bool,_ARR);
DEFINE_PRIM(_ARR,__array_copy_ref,_ARR);
DEFINE_PRIM(_ARR,__array_concat_i32,_ARR _ARR);
DEFINE_PRIM(_ARR,__array_concat_f64,_ARR _ARR);
DEFINE_PRIM(_ARR,__array_concat_bytes,_ARR _ARR);
DEFINE_PRIM(_ARR,__array_concat_bool,_ARR _ARR);
DEFINE_PRIM(_ARR,__array_concat_ref,_ARR _ARR);
DEFINE_PRIM(_ARR,__array_slice_i32,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_slice_f64,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_slice_bytes,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_slice_bool,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_slice_ref,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_splice_i32,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_splice_f64,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_splice_bytes,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_splice_bool,_ARR _I32 _I32);
DEFINE_PRIM(_ARR,__array_splice_ref,_ARR _I32 _I32);
DEFINE_PRIM(_I32,__array_index_of_i32,_ARR _I32);
DEFINE_PRIM(_I32,__array_index_of_f64,_ARR _F64);
DEFINE_PRIM(_I32,__array_index_of_bytes,_ARR _BYTES);
DEFINE_PRIM(_I32,__array_index_of_bool,_ARR _BOOL);
DEFINE_PRIM(_I32,__array_index_of_ref,_ARR _DYN);
DEFINE_PRIM(_BOOL,__array_remove_i32,_ARR _I32);
DEFINE_PRIM(_BOOL,__array_remove_f64,_ARR _F64);
DEFINE_PRIM(_BOOL,__array_remove_bytes,_ARR _BYTES);
DEFINE_PRIM(_BOOL,__array_remove_bool,_ARR _BOOL);
DEFINE_PRIM(_BOOL,__array_remove_ref,_ARR _DYN);
DEFINE_PRIM(_DYN,__reflect_field,_DYN _BYTES);
DEFINE_PRIM(_VOID,__reflect_set_field,_DYN _BYTES _DYN);
DEFINE_PRIM(_BOOL,__reflect_has_field,_DYN _BYTES);
DEFINE_PRIM(_I32,__reflect_field_count,_DYN);
DEFINE_PRIM(_BYTES,__reflect_field_name,_DYN _I32);
DEFINE_PRIM(_DYN,__reflect_dynamic_object,_NO_ARG);
DEFINE_PRIM(_BOOL,__reflect_is_function,_DYN);
DEFINE_PRIM(_DYN,__reflect_array_get,_DYN _I32);
DEFINE_PRIM(_I32,__json_value_kind,_DYN);
DEFINE_PRIM(_VOID,__array_reverse_i32,_ARR);
DEFINE_PRIM(_VOID,__array_reverse_f64,_ARR);
DEFINE_PRIM(_VOID,__array_reverse_bytes,_ARR);
DEFINE_PRIM(_VOID,__array_reverse_bool,_ARR);
DEFINE_PRIM(_VOID,__array_reverse_ref,_ARR);
DEFINE_PRIM(_I32,__array_push_i32,_ARR _I32);
DEFINE_PRIM(_I32,__array_unshift_i32,_ARR _I32);
DEFINE_PRIM(_VOID,__array_insert_i32,_ARR _I32 _I32);
DEFINE_PRIM(_I32,__array_pop_i32,_ARR);
DEFINE_PRIM(_I32,__array_shift_i32,_ARR);
DEFINE_PRIM(_I32,__array_push_f64,_ARR _F64);
DEFINE_PRIM(_I32,__array_unshift_f64,_ARR _F64);
DEFINE_PRIM(_VOID,__array_insert_f64,_ARR _I32 _F64);
DEFINE_PRIM(_F64,__array_pop_f64,_ARR);
DEFINE_PRIM(_F64,__array_shift_f64,_ARR);
DEFINE_PRIM(_I32,__array_push_bytes,_ARR _BYTES);
DEFINE_PRIM(_I32,__array_unshift_bytes,_ARR _BYTES);
DEFINE_PRIM(_VOID,__array_insert_bytes,_ARR _I32 _BYTES);
DEFINE_PRIM(_BYTES,__array_pop_bytes,_ARR);
DEFINE_PRIM(_BYTES,__array_shift_bytes,_ARR);
DEFINE_PRIM(_I32,__array_push_bool,_ARR _BOOL);
DEFINE_PRIM(_I32,__array_unshift_bool,_ARR _BOOL);
DEFINE_PRIM(_VOID,__array_insert_bool,_ARR _I32 _BOOL);
DEFINE_PRIM(_BOOL,__array_pop_bool,_ARR);
DEFINE_PRIM(_BOOL,__array_shift_bool,_ARR);
DEFINE_PRIM(_I32,__array_push_ref,_ARR _DYN);
DEFINE_PRIM(_I32,__array_unshift_ref,_ARR _DYN);
DEFINE_PRIM(_VOID,__array_insert_ref,_ARR _I32 _DYN);
DEFINE_PRIM(_DYN,__array_pop_ref,_ARR);
DEFINE_PRIM(_DYN,__array_shift_ref,_ARR);
DEFINE_PRIM(_VOID,__array_resize_i32,_ARR _I32);
DEFINE_PRIM(_VOID,__array_resize_f64,_ARR _I32);
DEFINE_PRIM(_VOID,__array_resize_bytes,_ARR _I32);
DEFINE_PRIM(_VOID,__array_resize_bool,_ARR _I32);
DEFINE_PRIM(_VOID,__array_resize_ref,_ARR _I32);
DEFINE_PRIM(_ABSTRACT(map_string_i32),__map_string_i32_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_string_i32_set,_ABSTRACT(map_string_i32) _BYTES _I32);
DEFINE_PRIM(_BOOL,__map_string_i32_exists,_ABSTRACT(map_string_i32) _BYTES);
DEFINE_PRIM(_DYN,__map_string_i32_get,_ABSTRACT(map_string_i32) _BYTES);
DEFINE_PRIM(_ABSTRACT(map_string_bool),__map_string_bool_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_string_bool_set,_ABSTRACT(map_string_bool) _BYTES _BOOL);
DEFINE_PRIM(_BOOL,__map_string_bool_exists,_ABSTRACT(map_string_bool) _BYTES);
DEFINE_PRIM(_DYN,__map_string_bool_get,_ABSTRACT(map_string_bool) _BYTES);
DEFINE_PRIM(_ABSTRACT(map_string_f64),__map_string_f64_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_string_f64_set,_ABSTRACT(map_string_f64) _BYTES _F64);
DEFINE_PRIM(_BOOL,__map_string_f64_exists,_ABSTRACT(map_string_f64) _BYTES);
DEFINE_PRIM(_DYN,__map_string_f64_get,_ABSTRACT(map_string_f64) _BYTES);
DEFINE_PRIM(_ABSTRACT(map_string_bytes),__map_string_bytes_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_string_bytes_set,_ABSTRACT(map_string_bytes) _BYTES _BYTES);
DEFINE_PRIM(_BOOL,__map_string_bytes_exists,_ABSTRACT(map_string_bytes) _BYTES);
DEFINE_PRIM(_DYN,__map_string_bytes_get,_ABSTRACT(map_string_bytes) _BYTES);
DEFINE_PRIM(_ARR,__map_string_i32_keys,_ABSTRACT(map_string_i32));
DEFINE_PRIM(_ARR,__map_string_bool_keys,_ABSTRACT(map_string_bool));
DEFINE_PRIM(_ARR,__map_string_f64_keys,_ABSTRACT(map_string_f64));
DEFINE_PRIM(_ARR,__map_string_bytes_keys,_ABSTRACT(map_string_bytes));
DEFINE_PRIM(_ARR,__map_string_i32_values,_ABSTRACT(map_string_i32));
DEFINE_PRIM(_ARR,__map_string_bool_values,_ABSTRACT(map_string_bool));
DEFINE_PRIM(_ARR,__map_string_f64_values,_ABSTRACT(map_string_f64));
DEFINE_PRIM(_ARR,__map_string_bytes_values,_ABSTRACT(map_string_bytes));
DEFINE_PRIM(_BOOL,__map_string_i32_remove,_ABSTRACT(map_string_i32) _BYTES);
DEFINE_PRIM(_BOOL,__map_string_bool_remove,_ABSTRACT(map_string_bool) _BYTES);
DEFINE_PRIM(_BOOL,__map_string_f64_remove,_ABSTRACT(map_string_f64) _BYTES);
DEFINE_PRIM(_BOOL,__map_string_bytes_remove,_ABSTRACT(map_string_bytes) _BYTES);
DEFINE_PRIM(_VOID,__map_string_i32_clear,_ABSTRACT(map_string_i32));
DEFINE_PRIM(_VOID,__map_string_bool_clear,_ABSTRACT(map_string_bool));
DEFINE_PRIM(_VOID,__map_string_f64_clear,_ABSTRACT(map_string_f64));
DEFINE_PRIM(_VOID,__map_string_bytes_clear,_ABSTRACT(map_string_bytes));
DEFINE_PRIM(_I32,__map_string_i32_size,_ABSTRACT(map_string_i32));
DEFINE_PRIM(_I32,__map_string_bool_size,_ABSTRACT(map_string_bool));
DEFINE_PRIM(_I32,__map_string_f64_size,_ABSTRACT(map_string_f64));
DEFINE_PRIM(_I32,__map_string_bytes_size,_ABSTRACT(map_string_bytes));
DEFINE_PRIM(_ABSTRACT(map_string_ref),__map_string_ref_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_string_ref_set,_ABSTRACT(map_string_ref) _BYTES _DYN);
DEFINE_PRIM(_BOOL,__map_string_ref_exists,_ABSTRACT(map_string_ref) _BYTES);
DEFINE_PRIM(_DYN,__map_string_ref_get,_ABSTRACT(map_string_ref) _BYTES);
DEFINE_PRIM(_ARR,__map_string_ref_keys,_ABSTRACT(map_string_ref));
DEFINE_PRIM(_ARR,__map_string_ref_values,_ABSTRACT(map_string_ref));
DEFINE_PRIM(_BOOL,__map_string_ref_remove,_ABSTRACT(map_string_ref) _BYTES);
DEFINE_PRIM(_VOID,__map_string_ref_clear,_ABSTRACT(map_string_ref));
DEFINE_PRIM(_I32,__map_string_ref_size,_ABSTRACT(map_string_ref));
DEFINE_PRIM(_ABSTRACT(map_int_i32),__map_int_i32_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_int_i32_set,_ABSTRACT(map_int_i32) _I32 _I32);
DEFINE_PRIM(_BOOL,__map_int_i32_exists,_ABSTRACT(map_int_i32) _I32);
DEFINE_PRIM(_DYN,__map_int_i32_get,_ABSTRACT(map_int_i32) _I32);
DEFINE_PRIM(_ABSTRACT(map_int_bool),__map_int_bool_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_int_bool_set,_ABSTRACT(map_int_bool) _I32 _BOOL);
DEFINE_PRIM(_BOOL,__map_int_bool_exists,_ABSTRACT(map_int_bool) _I32);
DEFINE_PRIM(_DYN,__map_int_bool_get,_ABSTRACT(map_int_bool) _I32);
DEFINE_PRIM(_ABSTRACT(map_int_f64),__map_int_f64_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_int_f64_set,_ABSTRACT(map_int_f64) _I32 _F64);
DEFINE_PRIM(_BOOL,__map_int_f64_exists,_ABSTRACT(map_int_f64) _I32);
DEFINE_PRIM(_DYN,__map_int_f64_get,_ABSTRACT(map_int_f64) _I32);
DEFINE_PRIM(_ABSTRACT(map_int_bytes),__map_int_bytes_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_int_bytes_set,_ABSTRACT(map_int_bytes) _I32 _BYTES);
DEFINE_PRIM(_BOOL,__map_int_bytes_exists,_ABSTRACT(map_int_bytes) _I32);
DEFINE_PRIM(_DYN,__map_int_bytes_get,_ABSTRACT(map_int_bytes) _I32);
DEFINE_PRIM(_ARR,__map_int_i32_keys,_ABSTRACT(map_int_i32));
DEFINE_PRIM(_ARR,__map_int_bool_keys,_ABSTRACT(map_int_bool));
DEFINE_PRIM(_ARR,__map_int_f64_keys,_ABSTRACT(map_int_f64));
DEFINE_PRIM(_ARR,__map_int_bytes_keys,_ABSTRACT(map_int_bytes));
DEFINE_PRIM(_ARR,__map_int_i32_values,_ABSTRACT(map_int_i32));
DEFINE_PRIM(_ARR,__map_int_bool_values,_ABSTRACT(map_int_bool));
DEFINE_PRIM(_ARR,__map_int_f64_values,_ABSTRACT(map_int_f64));
DEFINE_PRIM(_ARR,__map_int_bytes_values,_ABSTRACT(map_int_bytes));
DEFINE_PRIM(_BOOL,__map_int_i32_remove,_ABSTRACT(map_int_i32) _I32);
DEFINE_PRIM(_BOOL,__map_int_bool_remove,_ABSTRACT(map_int_bool) _I32);
DEFINE_PRIM(_BOOL,__map_int_f64_remove,_ABSTRACT(map_int_f64) _I32);
DEFINE_PRIM(_BOOL,__map_int_bytes_remove,_ABSTRACT(map_int_bytes) _I32);
DEFINE_PRIM(_VOID,__map_int_i32_clear,_ABSTRACT(map_int_i32));
DEFINE_PRIM(_VOID,__map_int_bool_clear,_ABSTRACT(map_int_bool));
DEFINE_PRIM(_VOID,__map_int_f64_clear,_ABSTRACT(map_int_f64));
DEFINE_PRIM(_VOID,__map_int_bytes_clear,_ABSTRACT(map_int_bytes));
DEFINE_PRIM(_I32,__map_int_i32_size,_ABSTRACT(map_int_i32));
DEFINE_PRIM(_I32,__map_int_bool_size,_ABSTRACT(map_int_bool));
DEFINE_PRIM(_I32,__map_int_f64_size,_ABSTRACT(map_int_f64));
DEFINE_PRIM(_I32,__map_int_bytes_size,_ABSTRACT(map_int_bytes));
DEFINE_PRIM(_ABSTRACT(map_int_ref),__map_int_ref_alloc,_NO_ARG);
DEFINE_PRIM(_VOID,__map_int_ref_set,_ABSTRACT(map_int_ref) _I32 _DYN);
DEFINE_PRIM(_BOOL,__map_int_ref_exists,_ABSTRACT(map_int_ref) _I32);
DEFINE_PRIM(_DYN,__map_int_ref_get,_ABSTRACT(map_int_ref) _I32);
DEFINE_PRIM(_ARR,__map_int_ref_keys,_ABSTRACT(map_int_ref));
DEFINE_PRIM(_ARR,__map_int_ref_values,_ABSTRACT(map_int_ref));
DEFINE_PRIM(_BOOL,__map_int_ref_remove,_ABSTRACT(map_int_ref) _I32);
DEFINE_PRIM(_VOID,__map_int_ref_clear,_ABSTRACT(map_int_ref));
DEFINE_PRIM(_I32,__map_int_ref_size,_ABSTRACT(map_int_ref));
DEFINE_PRIM(_BYTES,__string_concat,_BYTES _BYTES);
DEFINE_PRIM(_BOOL,__math_is_nan,_F64);
DEFINE_PRIM(_BOOL,__math_is_finite,_F64);
DEFINE_PRIM(_F64,__math_pow,_F64 _F64);
DEFINE_PRIM(_F64,__math_cos,_F64);
DEFINE_PRIM(_F64,__math_sin,_F64);
DEFINE_PRIM(_F64,__math_tan,_F64);
DEFINE_PRIM(_F64,__math_fmod,_F64 _F64);
DEFINE_PRIM(_I32,__math_round,_F64);
DEFINE_PRIM(_I32,__string_length,_BYTES);
DEFINE_PRIM(_BOOL,__string_equal,_BYTES _BYTES);
DEFINE_PRIM(_I32,__string_index_of,_BYTES _BYTES);
DEFINE_PRIM(_I32,__string_index_of_from,_BYTES _BYTES _I32);
DEFINE_PRIM(_ARR,__string_split,_BYTES _BYTES);
DEFINE_PRIM(_BYTES,__string_ltrim,_BYTES);
DEFINE_PRIM(_BYTES,__string_trim,_BYTES);
DEFINE_PRIM(_BYTES,__string_to_lower_case,_BYTES);
DEFINE_PRIM(_BYTES,__string_to_upper_case,_BYTES);
DEFINE_PRIM(_BOOL,__string_is_space,_BYTES _I32);
DEFINE_PRIM(_I32,__string_last_index_of,_BYTES _BYTES);
DEFINE_PRIM(_I32,__string_char_code_at,_BYTES _I32);
DEFINE_PRIM(_BYTES,__string_char_at,_BYTES _I32);
DEFINE_PRIM(_BYTES,__string_from_char_code,_I32);
DEFINE_PRIM(_BYTES,__string_from_bytes,_BYTES _I32);
DEFINE_PRIM(_BYTES,__string_bytes,_BYTES);
DEFINE_PRIM(_I32,__std_parse_int,_BYTES);
DEFINE_PRIM(_F64,__std_parse_float,_BYTES);
DEFINE_PRIM(_I32,__std_int_f64,_F64);
DEFINE_PRIM(_I32,__std_random,_I32);
DEFINE_PRIM(_BYTES,__std_string,_DYN);
DEFINE_PRIM(_I32,__reflect_compare,_DYN _DYN);
DEFINE_PRIM(_BOOL,__dynamic_equal,_DYN _DYN);
DEFINE_PRIM(_BOOL,__string_starts_with,_BYTES _BYTES);
DEFINE_PRIM(_BOOL,__string_ends_with,_BYTES _BYTES);
DEFINE_PRIM(_BYTES,__string_replace,_BYTES _BYTES _BYTES);
DEFINE_PRIM(_BYTES,__file_get_content,_BYTES);
DEFINE_PRIM(_VOID,__file_save_content,_BYTES _BYTES);
DEFINE_PRIM(_BYTES,__file_write_atomic,_BYTES _ABSTRACT(realtime_bytes) _BOOL);
DEFINE_PRIM(_BYTES,__sys_get_cwd,_NO_ARG);
DEFINE_PRIM(_BYTES,__sys_full_path,_BYTES);
DEFINE_PRIM(_BYTES,__sys_exe_path,_NO_ARG);
DEFINE_PRIM(_BOOL,__sys_exists,_BYTES);
DEFINE_PRIM(_BOOL,__sys_is_dir,_BYTES);
DEFINE_PRIM(_BOOL,__sys_set_cwd,_BYTES);
DEFINE_PRIM(_BOOL,__sys_create_dir,_BYTES _I32);
DEFINE_PRIM(_BOOL,__sys_remove_dir,_BYTES);
DEFINE_PRIM(_BOOL,__sys_delete,_BYTES);
DEFINE_PRIM(_BOOL,__sys_rename,_BYTES _BYTES);
DEFINE_PRIM(_ARR,__sys_read_dir,_BYTES);
DEFINE_PRIM(_ARR,__sys_metadata,_BYTES);
DEFINE_PRIM(_BYTES,__sys_get_env,_BYTES);
DEFINE_PRIM(_BYTES,__sys_system_name,_NO_ARG);
DEFINE_PRIM(_BOOL,__sys_put_env,_BYTES _BYTES);
DEFINE_PRIM(_I32,__sys_command,_BYTES);
DEFINE_PRIM(_VOID,__sys_print,_BYTES);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),__bytes_alloc,_I32);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),__bytes_of_string,_BYTES);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),__bytes_view,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_I32,__bytes_length,_ABSTRACT(realtime_bytes));
DEFINE_PRIM(_BYTES,__bytes_get_data,_ABSTRACT(realtime_bytes));
DEFINE_PRIM(_I32,__bytes_get,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_I32,getI8,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,setI8,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_I32,getU8,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,setU8,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_I32,getI16,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,setI16,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_I32,getU16,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,setU16,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_I32,getI32,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,setI32,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_I64,getI64,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,setI64,_ABSTRACT(realtime_bytes) _I32 _I64);
DEFINE_PRIM(_F64,getF32,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,setF32,_ABSTRACT(realtime_bytes) _I32 _F64);
DEFINE_PRIM(_F64,getF64,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,setF64,_ABSTRACT(realtime_bytes) _I32 _F64);
DEFINE_PRIM(_I32,__bytes_get_i32,_ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_VOID,__bytes_set,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_VOID,__bytes_set_i32,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),__bytes_sub,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),structSlice,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_VOID,structCopy,_ABSTRACT(realtime_bytes) _I32 _ABSTRACT(realtime_bytes) _I32);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),structCopyPointer,_ABSTRACT(realtime_bytes) _I32 _I32 _I32);
DEFINE_PRIM(_I32,__bytes_compare,_ABSTRACT(realtime_bytes) _ABSTRACT(realtime_bytes));
DEFINE_PRIM(_BYTES,__bytes_to_string,_ABSTRACT(realtime_bytes));
DEFINE_PRIM(_BYTES,__bytes_get_string,_ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_ARR,__sys_args,_NO_ARG);
DEFINE_PRIM(_ABSTRACT(realtime_bytes_input),__bytes_input_new,_ABSTRACT(realtime_bytes));
DEFINE_PRIM(_I32,__bytes_input_position,_ABSTRACT(realtime_bytes_input));
DEFINE_PRIM(_BOOL,__bytes_input_big_endian,_ABSTRACT(realtime_bytes_input));
DEFINE_PRIM(_VOID,__bytes_input_set_big_endian,_ABSTRACT(realtime_bytes_input) _BOOL);
DEFINE_PRIM(_I32,__bytes_input_read_byte,_ABSTRACT(realtime_bytes_input));
DEFINE_PRIM(_I32,__bytes_input_read_i32,_ABSTRACT(realtime_bytes_input));
DEFINE_PRIM(_F64,__bytes_input_read_f64,_ABSTRACT(realtime_bytes_input));
DEFINE_PRIM(_BYTES,__bytes_input_read_string,_ABSTRACT(realtime_bytes_input) _I32);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),__bytes_input_read,_ABSTRACT(realtime_bytes_input) _I32);
DEFINE_PRIM(_ABSTRACT(realtime_bytes_output),__bytes_output_new,_NO_ARG);
DEFINE_PRIM(_BOOL,__bytes_output_big_endian,_ABSTRACT(realtime_bytes_output));
DEFINE_PRIM(_VOID,__bytes_output_set_big_endian,_ABSTRACT(realtime_bytes_output) _BOOL);
DEFINE_PRIM(_VOID,__bytes_output_write_byte,_ABSTRACT(realtime_bytes_output) _I32);
DEFINE_PRIM(_VOID,__bytes_output_write_i32,_ABSTRACT(realtime_bytes_output) _I32);
DEFINE_PRIM(_VOID,__bytes_output_write_f64,_ABSTRACT(realtime_bytes_output) _F64);
DEFINE_PRIM(_VOID,__bytes_output_write_string,_ABSTRACT(realtime_bytes_output) _BYTES);
DEFINE_PRIM(_VOID,__bytes_output_write,_ABSTRACT(realtime_bytes_output) _ABSTRACT(realtime_bytes));
DEFINE_PRIM(_I32,__bytes_output_write_range,_ABSTRACT(realtime_bytes_output) _ABSTRACT(realtime_bytes) _I32 _I32);
DEFINE_PRIM(_ABSTRACT(realtime_bytes),__bytes_output_get_bytes,_ABSTRACT(realtime_bytes_output));
DEFINE_PRIM(_VOID,__file_save_bytes,_BYTES _ABSTRACT(realtime_bytes));
DEFINE_PRIM(_ABSTRACT(realtime_bytes),__file_get_bytes,_BYTES);
DEFINE_PRIM(_ABSTRACT(realtime_date),__date_now,_NO_ARG);
DEFINE_PRIM(_F64,__date_get_time,_ABSTRACT(realtime_date));
DEFINE_PRIM(_BYTES,__array_join_bytes,_ARR _BYTES);
DEFINE_PRIM(_BYTES,__string_substring,_BYTES _I32 _I32);
DEFINE_PRIM(_BOOL,__exception_matches,_DYN _TYPE);
DEFINE_PRIM(_BOOL,__std_is_of_type,_DYN _TYPE);
