import compiler.ffi.CHeaderImporter;
import compiler.ffi.CxxHeaderImporter;
import compiler.ffi.CxxProjection;
import compiler.ffi.HxiWriter;
import haxe.io.Path;
import sys.io.File;
import sys.FileSystem;

/** Standalone C/C++ header to raw-HXI importer. */
class FfiImportMain {
	static function main():Void {
		var args = Sys.args(), target = "", output = "", language = "c", standard = "c11", clang = "clang", compileCommands:Null<String> = null,
			library:Null<String> = null, interfaceName:Null<String> = null, includes:Array<String> = [], defines:Array<String> = [],
			dependencies:Array<String> = [], sourceLabel:Null<String> = null, excludedHeaders:Array<String> = [], paths:Array<String> = [],
			trivialValues = false, cxxLifetimes = false, haxeOutputDir:Null<String> = null;
		for (arg in args)
			if (StringTools.startsWith(arg, "--target="))
				target = arg.substring(9);
			else if (StringTools.startsWith(arg, "--language="))
				language = arg.substring(11);
			else if (StringTools.startsWith(arg, "--std="))
				standard = arg.substring(6);
			else if (StringTools.startsWith(arg, "--clang="))
				clang = arg.substring(8);
			else if (StringTools.startsWith(arg, "--output="))
				output = arg.substring(9);
			else if (StringTools.startsWith(arg, "--include="))
				includes.push(arg.substring(10));
			else if (StringTools.startsWith(arg, "--define="))
				defines.push(arg.substring(9));
			else if (StringTools.startsWith(arg, "--compile-commands="))
				compileCommands = arg.substring(arg.indexOf("=") + 1);
			else if (arg == "--cxx-trivial-values")
				trivialValues = true;
			else if (arg == "--cxx-lifetimes")
				cxxLifetimes = true;
			else if (StringTools.startsWith(arg, "--library="))
				library = arg.substring(10);
			else if (StringTools.startsWith(arg, "--interface="))
				interfaceName = arg.substring(12);
			else if (StringTools.startsWith(arg, "--depends="))
				dependencies.push(arg.substring(10));
			else if (StringTools.startsWith(arg, "--source-label="))
				sourceLabel = arg.substring(15);
			else if (StringTools.startsWith(arg, "--haxe-output-dir="))
				haxeOutputDir = arg.substring(arg.indexOf("=") + 1);
			else if (StringTools.startsWith(arg, "--exclude-header="))
				excludedHeaders.push(arg.substring(17));
			else if (StringTools.startsWith(arg, "--"))
				throw 'Unknown FFI import option "$arg"';
			else
				paths.push(arg);
		if (language != "c" && language != "c++")
			throw 'Unsupported FFI language "$language"';
		if (haxeOutputDir != null && language != "c++")
			throw "--haxe-output-dir requires --language=c++";
		if (haxeOutputDir != null && library == null)
			throw "--haxe-output-dir requires --library so generated wrappers can call the HXI interface";
		if (language == "c++" && clang == "clang")
			clang = "clang++";
		if (target.length == 0 || output.length == 0 || paths.length != 1)
			throw "Usage: haxeon-ffi-import --language=c|c++ --target=<triple> --output=<file> [--std=<standard>] [--clang=<path>] [--cxx-trivial-values] [--cxx-lifetimes] [--library=<name>] [--interface=<name>] [--haxe-output-dir=<directory>] [--depends=<interface>] [--include=<dir>] [--define=<name[=value]>] [--compile-commands=<path>] [--source-label=<path>] [--exclude-header=<path>] <header>";
		var cxxResult = language == "c++" ? CxxHeaderImporter.importHeader(paths[0], target, includes, clang, library, interfaceName, dependencies,
			excludedHeaders, standard, defines, compileCommands, trivialValues, cxxLifetimes) : null,
			model = cxxResult == null ? CHeaderImporter.importHeaderWithOptions(paths[0], target, includes, clang, library, interfaceName, dependencies,
				excludedHeaders, defines, compileCommands) : cxxResult.hxi,
			label = sourceLabel == null ? paths[0] : sourceLabel,
			headerComment = '// Generated by Haxeon from $label for $target. Do not edit.';
		File.saveContent(output, HxiWriter.write(model, headerComment));
		if (haxeOutputDir != null) {
			if (!FileSystem.exists(haxeOutputDir))
				FileSystem.createDirectory(haxeOutputDir);
			for (projection in CxxProjection.sources(cxxResult.model, cxxResult.hxi, null, cxxResult.plans))
				File.saveContent(Path.join([haxeOutputDir, projection.file]), projection.source);
		}
		Sys.println('imported ${paths[0]} -> $output');
	}
}
